<a href="https://colab.research.google.com/github/zimin205/BDA_Data/blob/main/10%EA%B8%B0%EC%A0%84%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!ls "/content/drive/MyDrive/BDA 6기 운영진/6기 데이터팀/"

'10기 응답폼_중복제거.xlsx'  '마케팅팀_인스타그램 분석 요청'
'5기 데이터팀'		      보고서
'9기 학회원 만족도 조사'      서베이
'9기 학회원 최종 과제'	     '제목 없는 설문지.gform'
 code			     '학술 대회'
 김지민

In [ ]:
file_path = '/content/drive/MyDrive/BDA 6기 운영진/6기 데이터팀/김지민/10기응답폼.xlsx'

In [ ]:
# Excel 파일 불러오기
df10 = pd.read_excel(file_path, dtype={'phone_number': str})
# 열 목록 추출
df10col_list = df10.columns.to_list()

# DataFrame으로 변환
df10col = pd.DataFrame(df10col_list, columns=['df10col'])

# 데이터프레임 확인
print(df10.head())

# 열 목록 확인
print(df10col)

  내/외국인 성별    birthday    거주지   세부 거주지   직업   이름        전화번호  \
0   내국인  여  20040707.0  서울특별시  서울시 노원구  대학생  김태희  1035608290
1   내국인  여  20010726.0  서울특별시      도봉구  대학생  이주은  1096913787
2   내국인  남  20001213.0    경기도      파주시  대학생  이건희  1073542251
3   내국인  남  20040618.0  인천광역시    인천광역시  대학생  박준형  1086869796
4   내국인  남  20010331.0  서울특별시      성북구  대학생  류지현  1093463517

                          이메일     최종학력  ...                  현직자 기업 수준  \
0        heehee8290@gmail.com  고등학교 졸업  ...  국내 대기업 IT 계열 (금융, 제조 ...)
1          jeul0854@gmail.com   대학교 학사  ...               스타트업 C-level
2         ghdec1213@gmail.com   대학교 학사  ...  국내 대기업 IT 계열 (금융, 제조 ...)
3  parkjunhyung6018@naver.com   대학교 학사  ...     국내 빅테크 IT 계열 (네카라쿠배당토)
4          iami3517@gmail.com   대학교 학사  ...  국내 대기업 IT 계열 (금융, 제조 ...)

    현직자 강의 형식                  현직자 강의 규모                        규모 선택 이유(현직자)  \
0        오프라인  3~50명 내외의 강의 리스너와 1명의 현직자                   수업집중에 적절한 인원인 듯 하여
1  온, 오프라인 동시  3~50명 내외의 강의 리스너와 1명의 현직자             인원이 너무 많으면 집중이 분산될 것 같아서
2  온, 오프라인 동시  3~50명 내외의 강의 리스너와 1명의 현직자  1명의 현직자와 다수간의 강의가 더 원활하게 진행되는 것 같아서
3  온, 오프라인 동시  100명 이상의 리스너와 10명 이상의 현직자       인원이 많아야 참여할 수 있는 기회가 더 많아지기 때문
4  온, 오프라인 동시  100명 이상의 리스너와 10명 이상의 현직자                      더 다양한 경험을 듣기 위해

  데이터 분석 대회 경험 공모전 성능 향상 방법  아이디어 공모전 기획 방법 공모전 수상 경력 원하는 행사(공멘토) whyBDA(공멘토)
0          NaN          NaN             NaN       NaN         NaN         NaN
1          NaN          NaN             NaN       NaN         NaN         NaN
2          NaN          NaN             NaN       NaN         NaN         NaN
3          NaN          NaN             NaN       NaN         NaN         NaN
4          NaN          NaN             NaN       NaN         NaN         NaN

[5 rows x 123 columns]
            df10col
0             내/외국인
1                성별
2          birthday
3               거주지
4            세부 거주지
..              ...
118    공모전 성능 향상 방법
119  아이디어 공모전 기획 방법
120       공모전 수상 경력
121     원하는 행사(공멘토)
122     whyBDA(공멘토)

[123 rows x 1 columns]

In [ ]:
save_path_drive = "/content/drive/MyDrive/df10col.xlsx"
df10col.to_excel(save_path_drive, index=False)
print(f"Google 드라이브에 저장되었습니다: {save_path_drive}")

Google 드라이브에 저장되었습니다: /content/drive/MyDrive/df10col.xlsx

In [ ]:
file_path = '/content/drive/MyDrive/BDA 6기 운영진/6기 데이터팀/김지민/10기응답폼.xlsx'

In [ ]:
# 엑셀 파일 불러오기
df = pd.read_excel(file_path)

# 모든 컬럼명 출력
print(df.columns.tolist())

['내/외국인', '성별', 'birthday', '거주지', '세부 거주지', '직업', '이름', '전화번호', '이메일', '최종학력', '재학 여부(석사)', 'school2', '단과 대학(석사)', 'major2', '재학 여부(학사)', '휴학 이유', '이수학기', '수강학점', 'school1', '단과 대학(학사)', 'major1_1', 'major type', 'major1_2', 'major1_3', '원하는 분반 개수', '원하는 활동(일반)', '원하는 분반 번호(1개)', '분반 선택 이유(1개)', '원하는 분반 번호(2개_1)', '분반 선택 이유(2개_1)', '원하는 분반 번호(2개_2)', '분반 선택 이유(2개_2)', '원하는 분반 번호(3개_1)', '분반 선택 이유(3개_1)', '원하는 분반 번호(3개_2)', '분반 선택 이유(3개_2)', '원하는 분반 번호(3개_3)', '분반 선택 이유(3개_3)', '유입경로', 'BDA를 알게된 인스타그램 콘텐츠', '콘텐츠를 보게 된 경로', '관심을 끌었던 인스타그램 콘텐츠', '관심이 없었던 인스타그램 콘텐츠', '등록 결정 이유(인스타그램)', '보고싶은 컨텐츠', 'whyBDA', '재등록 여부', '기존 분반[3기]', '기존 분반[4기]', '기존 분반[5기]', '기존 분반[6기]', '기존 분반[7기]', '기존 분반[8기]', '기존 분반[9기]', '가장 만족한 활동(재등록)', '기대되는 활동(재등록)', '만족, 기대 답변 이유(재등록)', 'whyBDA(재등록)', '프로젝트 형태', '조별활동 희망', '투입 가능 시간', '얻고자 하는 것', 'job_domain', 'company', '직업 형태(현재직장)', '근무 연차(현재직장)', 'whyBDA(현재직장)', '데이터 분석 역량 필요 이유(현재직장)', '직장 도메인(이전직장)', '직업명(이전직장)', '근무 연차(이전직장)', '데이터 분석 역량 필요 이유(이전직장)', '희망 진로', '희망 도메인', '희망 직무', '희망 직무 데이터 역량', '관심있는 기업명', '언어 숙련도(SQL)', '언어 숙련도(Python)', '언어 숙련도(R)', '패키지 숙련도(Pandas)', '패키지 숙련도(Numpy)', '패키지 숙련도(Scikit-learn)', '패키지 숙련도(Pytorch)', '패키지 숙련도(TensorFlow)', '패키지 숙련도(Keras)', '시각화 도구 숙련도(Looker Studio)', '시각화 도구 숙련도(Tableau)', '시각화 도구 숙련도(Power BI)', '시각화 도구 숙련도(Python 시각화 라이브러리)', '취득 자격증', '취득 희망 자격증', '희망 자격증 스터디 기간', '데이터 관련 활동 경험(스터디)', '데이터 관련 활동 경험(동아리)', '데이터 관련 활동 경험(학회)', '아쉬웠던 점(활동 중)', '데이터 관련 대회 경험(공모전)', '데이터 관련 대회 경험(프로젝트)', '아쉬웠던 점', '관심있는 채용 프로그램', '그 밖의 채용 프로그램', '원데이 클래스 주제', '원데이 클래스 강의 형식', '원데이 클래스 난이도', '원데이 클래스 참여할 의향', '원데이 클래스 요청 사항', 'BDA WAVE 추가 컨텐츠', '학술제 참여 의사', '학술제 컨텐츠', '데이터 외 희망 직무', '원하는 현직자 수준', '원하는 현직자 강의 주제', '현직자 기업 수준', '현직자 강의 형식', '현직자 강의 규모', '규모 선택 이유(현직자)', '데이터 분석 대회 경험', '공모전 성능 향상 방법', '아이디어 공모전 기획 방법', '공모전 수상 경력', '원하는 행사(공멘토)', 'whyBDA(공멘토)']

In [ ]:
#응답폼 식별자 만들기

응답폼 = pd.read_excel(file_path, dtype = {'전화번호' : str, 'birthday' : str})

응답폼['이름'] = 응답폼['이름'].str.strip()
응답폼['식별자'] = 응답폼['이름'] + '_' + 응답폼['전화번호'].astype(str).str[-4:-2]


#응답폼 중복 삭제
응답폼 = 응답폼.drop_duplicates(subset=[ '이메일'], keep='last')
응답폼 = 응답폼.drop_duplicates(subset=[ '전화번호'], keep='last')

In [ ]:
# 중복 제거 후 행 갯수 출력
print(f"중복 제거 후 행 갯수: {len(응답폼)}")

중복 제거 후 행 갯수: 1046

In [ ]:
# 저장할 파일 경로 지정
save_path = '/content/drive/MyDrive/BDA 6기 운영진/6기 데이터팀/10기 응답폼_중복제거.xlsx'

# 엑셀 파일로 저장
응답폼.to_excel(save_path, index=False)

print(f"파일이 저장되었습니다: {save_path}")

파일이 저장되었습니다: /content/drive/MyDrive/BDA 6기 운영진/6기 데이터팀/10기 응답폼_중복제거.xlsx

In [ ]:
print(응답폼.columns.tolist())  # 다시 확인

['내/외국인', '성별', 'birthday', '거주지', '세부 거주지', '직업', '이름', '전화번호', '이메일', '최종학력', '재학 여부(석사)', 'school2', '단과 대학(석사)', 'major2', '재학 여부(학사)', '휴학 이유', '이수학기', '수강학점', 'school1', '단과 대학(학사)', 'major1_1', 'major type', 'major1_2', 'major1_3', '원하는 분반 개수', '원하는 활동(일반)', '원하는 분반 번호(1개)', '분반 선택 이유(1개)', '원하는 분반 번호(2개_1)', '분반 선택 이유(2개_1)', '원하는 분반 번호(2개_2)', '분반 선택 이유(2개_2)', '원하는 분반 번호(3개_1)', '분반 선택 이유(3개_1)', '원하는 분반 번호(3개_2)', '분반 선택 이유(3개_2)', '원하는 분반 번호(3개_3)', '분반 선택 이유(3개_3)', '유입경로', 'BDA를 알게된 인스타그램 콘텐츠', '콘텐츠를 보게 된 경로', '관심을 끌었던 인스타그램 콘텐츠', '관심이 없었던 인스타그램 콘텐츠', '등록 결정 이유(인스타그램)', '보고싶은 컨텐츠', 'whyBDA', '재등록 여부', '기존 분반[3기]', '기존 분반[4기]', '기존 분반[5기]', '기존 분반[6기]', '기존 분반[7기]', '기존 분반[8기]', '기존 분반[9기]', '가장 만족한 활동(재등록)', '기대되는 활동(재등록)', '만족, 기대 답변 이유(재등록)', 'whyBDA(재등록)', '프로젝트 형태', '조별활동 희망', '투입 가능 시간', '얻고자 하는 것', 'job_domain', 'company', '직업 형태(현재직장)', '근무 연차(현재직장)', 'whyBDA(현재직장)', '데이터 분석 역량 필요 이유(현재직장)', '직장 도메인(이전직장)', '직업명(이전직장)', '근무 연차(이전직장)', '데이터 분석 역량 필요 이유(이전직장)', '희망 진로', '희망 도메인', '희망 직무', '희망 직무 데이터 역량', '관심있는 기업명', '언어 숙련도(SQL)', '언어 숙련도(Python)', '언어 숙련도(R)', '패키지 숙련도(Pandas)', '패키지 숙련도(Numpy)', '패키지 숙련도(Scikit-learn)', '패키지 숙련도(Pytorch)', '패키지 숙련도(TensorFlow)', '패키지 숙련도(Keras)', '시각화 도구 숙련도(Looker Studio)', '시각화 도구 숙련도(Tableau)', '시각화 도구 숙련도(Power BI)', '시각화 도구 숙련도(Python 시각화 라이브러리)', '취득 자격증', '취득 희망 자격증', '희망 자격증 스터디 기간', '데이터 관련 활동 경험(스터디)', '데이터 관련 활동 경험(동아리)', '데이터 관련 활동 경험(학회)', '아쉬웠던 점(활동 중)', '데이터 관련 대회 경험(공모전)', '데이터 관련 대회 경험(프로젝트)', '아쉬웠던 점', '관심있는 채용 프로그램', '그 밖의 채용 프로그램', '원데이 클래스 주제', '원데이 클래스 강의 형식', '원데이 클래스 난이도', '원데이 클래스 참여할 의향', '원데이 클래스 요청 사항', 'BDA WAVE 추가 컨텐츠', '학술제 참여 의사', '학술제 컨텐츠', '데이터 외 희망 직무', '원하는 현직자 수준', '원하는 현직자 강의 주제', '현직자 기업 수준', '현직자 강의 형식', '현직자 강의 규모', '규모 선택 이유(현직자)', '데이터 분석 대회 경험', '공모전 성능 향상 방법', '아이디어 공모전 기획 방법', '공모전 수상 경력', '원하는 행사(공멘토)', 'whyBDA(공멘토)', '식별자']

In [ ]:
file_path = '/content/drive/MyDrive/BDA 6기 운영진/6기 데이터팀/김지민/10기 출석표.xlsx'


출석표 = pd.read_excel(file_path, dtype={'phone_number': str})

In [ ]:
import pandas as pd

# "분반" 컬럼을 사용하여 데이터 정리
출석표_강의 = 출석표[['식별자', '분반']].dropna().drop_duplicates()
출석표_강의 = 출석표_강의.groupby('식별자')['분반'].apply(list).reset_index()

# class1_update, class2_update, class3_update, class4_update 컬럼 생성
for idx, row in 출석표_강의.iterrows():
    분반명_list = row['분반']

    # class1_update부터 class4_update까지 업데이트
    for i in range(4):
        if i < len(분반명_list):
            출석표_강의.at[idx, f'class{i+1}'] = 분반명_list[i]
        else:
            출석표_강의.at[idx, f'class{i+1}'] = None

# 숫자만 변환하는 함수 정의
def convert_to_int_or_keep(value):
    if isinstance(value, str) and value.isdigit():  # 문자열이 숫자로만 되어 있으면 변환
        return int(value)
    return value  # 변환 불가능하면 그대로 반환

# class1~class4 컬럼에 적용
for i in range(1, 5):
    column_name = f'class{i}'
    출석표_강의[column_name] = 출석표_강의[column_name].apply(convert_to_int_or_keep)

print(출석표_강의)  # 결과 확인

                                    식별자            분반 class1 class2  class3  \
0       Hannah Safiah Binti Saharani_16        [0001]      1   None     NaN
1                      Ngoc Vu (알렉스)_36        [0014]     14   None     NaN
2    Nur Izzatty Binti Mohamad Jamal_49        [0001]      1   None     NaN
3                                강동운_97        [0015]     15   None     NaN
4                                강두원_75        [0004]      4   None     NaN
..                                  ...           ...    ...    ...     ...
913                              황정민_86        [0002]      2   None     NaN
914                              황종서_34        [0004]      4   None     NaN
915                              황준영_86  [0004, 0016]      4     16     NaN
916                              황지영_23  [0004, 0005]      4      5     NaN
917                              황지희_73  [0012, 0015]     12     15     NaN

     class4
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
..      ...
913     NaN
914     NaN
915     NaN
916     NaN
917     NaN

[918 rows x 6 columns]

In [ ]:
print(출석표.columns)  # 현재 데이터프레임의 컬럼 확인

Index(['분반', '식별자', '이름', '전화번호', '이메일', '소속대학', '비고', 'Unnamed: 7',
       'Unnamed: 8', 'Unnamed: 9'],
      dtype='object')

In [ ]:
출석표 = pd.merge(출석표_강의, 출석표, on = '식별자', how = 'left')
출석표= 출석표.drop_duplicates(subset=[ '식별자'], keep='last')

In [ ]:
출석표.columns = 출석표.columns.str.strip()  # 모든 컬럼명 공백 제거
print(출석표.columns.tolist())  # 다시 확인

['식별자', '분반_x', 'class1', 'class2', 'class3', 'class4', '분반_y', '이름', '전화번호', '이메일', '소속대학', '비고', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9']

In [ ]:
# 원하는 컬럼만 선택
출석표 = 출석표[['이름', '이메일', '전화번호', '소속대학', '식별자', 'class1', 'class2', 'class3', 'class4']]

In [ ]:
print(출석표.columns)  # 현재 데이터프레임의 컬럼 확인

Index(['이름', '이메일', '전화번호', '소속대학', '식별자', 'class1', 'class2', 'class3',
       'class4'],
      dtype='object')

In [ ]:
# 중복 제거 후 행 갯수 출력
print(f"중복 제거 후 행 갯수: {len(출석표)}")

중복 제거 후 행 갯수: 918

In [ ]:
df = pd.merge(출석표, 응답폼, on = ['식별자'], how = 'left')

In [ ]:
print(df.columns.tolist())  # df의 모든 컬럼 출력

['이름_x', '이메일_x', '전화번호_x', '소속대학', '식별자', 'class1', 'class2', 'class3', 'class4', '내/외국인', '성별', 'birthday', '거주지', '세부 거주지', '직업', '이름_y', '전화번호_y', '이메일_y', '최종학력', '재학 여부(석사)', 'school2', '단과 대학(석사)', 'major2', '재학 여부(학사)', '휴학 이유', '이수학기', '수강학점', 'school1', '단과 대학(학사)', 'major1_1', 'major type', 'major1_2', 'major1_3', '원하는 분반 개수', '원하는 활동(일반)', '원하는 분반 번호(1개)', '분반 선택 이유(1개)', '원하는 분반 번호(2개_1)', '분반 선택 이유(2개_1)', '원하는 분반 번호(2개_2)', '분반 선택 이유(2개_2)', '원하는 분반 번호(3개_1)', '분반 선택 이유(3개_1)', '원하는 분반 번호(3개_2)', '분반 선택 이유(3개_2)', '원하는 분반 번호(3개_3)', '분반 선택 이유(3개_3)', '유입경로', 'BDA를 알게된 인스타그램 콘텐츠', '콘텐츠를 보게 된 경로', '관심을 끌었던 인스타그램 콘텐츠', '관심이 없었던 인스타그램 콘텐츠', '등록 결정 이유(인스타그램)', '보고싶은 컨텐츠', 'whyBDA', '재등록 여부', '기존 분반[3기]', '기존 분반[4기]', '기존 분반[5기]', '기존 분반[6기]', '기존 분반[7기]', '기존 분반[8기]', '기존 분반[9기]', '가장 만족한 활동(재등록)', '기대되는 활동(재등록)', '만족, 기대 답변 이유(재등록)', 'whyBDA(재등록)', '프로젝트 형태', '조별활동 희망', '투입 가능 시간', '얻고자 하는 것', 'job_domain', 'company', '직업 형태(현재직장)', '근무 연차(현재직장)', 'whyBDA(현재직장)', '데이터 분석 역량 필요 이유(현재직장)', '직장 도메인(이전직장)', '직업명(이전직장)', '근무 연차(이전직장)', '데이터 분석 역량 필요 이유(이전직장)', '희망 진로', '희망 도메인', '희망 직무', '희망 직무 데이터 역량', '관심있는 기업명', '언어 숙련도(SQL)', '언어 숙련도(Python)', '언어 숙련도(R)', '패키지 숙련도(Pandas)', '패키지 숙련도(Numpy)', '패키지 숙련도(Scikit-learn)', '패키지 숙련도(Pytorch)', '패키지 숙련도(TensorFlow)', '패키지 숙련도(Keras)', '시각화 도구 숙련도(Looker Studio)', '시각화 도구 숙련도(Tableau)', '시각화 도구 숙련도(Power BI)', '시각화 도구 숙련도(Python 시각화 라이브러리)', '취득 자격증', '취득 희망 자격증', '희망 자격증 스터디 기간', '데이터 관련 활동 경험(스터디)', '데이터 관련 활동 경험(동아리)', '데이터 관련 활동 경험(학회)', '아쉬웠던 점(활동 중)', '데이터 관련 대회 경험(공모전)', '데이터 관련 대회 경험(프로젝트)', '아쉬웠던 점', '관심있는 채용 프로그램', '그 밖의 채용 프로그램', '원데이 클래스 주제', '원데이 클래스 강의 형식', '원데이 클래스 난이도', '원데이 클래스 참여할 의향', '원데이 클래스 요청 사항', 'BDA WAVE 추가 컨텐츠', '학술제 참여 의사', '학술제 컨텐츠', '데이터 외 희망 직무', '원하는 현직자 수준', '원하는 현직자 강의 주제', '현직자 기업 수준', '현직자 강의 형식', '현직자 강의 규모', '규모 선택 이유(현직자)', '데이터 분석 대회 경험', '공모전 성능 향상 방법', '아이디어 공모전 기획 방법', '공모전 수상 경력', '원하는 행사(공멘토)', 'whyBDA(공멘토)']

In [ ]:
print(df[['전화번호_x', '전화번호_y']].head())

       전화번호_x       전화번호_y
0  1058631610  01058631610
1  1073063668  01073063668
2  1097694955  01097694955
3  1085059745  01085059745
4  1063197508  01063197508

In [ ]:
# 응답폼 유무 확인 (이름이 NaN이면 False, 아니면 True)
df['응답폼유무'] = df['이름_y'].notna()
# school1 값 보완 (응답폼 값이 없으면 출석표 값 사용)
df['school1'] = df['school1'].fillna(df['소속대학'])
# 최종 컬럼 확인
print(df.columns.tolist())

['이름_x', '이메일_x', '전화번호_x', '소속대학', '식별자', 'class1', 'class2', 'class3', 'class4', '내/외국인', '성별', 'birthday', '거주지', '세부 거주지', '직업', '이름_y', '전화번호_y', '이메일_y', '최종학력', '재학 여부(석사)', 'school2', '단과 대학(석사)', 'major2', '재학 여부(학사)', '휴학 이유', '이수학기', '수강학점', 'school1', '단과 대학(학사)', 'major1_1', 'major type', 'major1_2', 'major1_3', '원하는 분반 개수', '원하는 활동(일반)', '원하는 분반 번호(1개)', '분반 선택 이유(1개)', '원하는 분반 번호(2개_1)', '분반 선택 이유(2개_1)', '원하는 분반 번호(2개_2)', '분반 선택 이유(2개_2)', '원하는 분반 번호(3개_1)', '분반 선택 이유(3개_1)', '원하는 분반 번호(3개_2)', '분반 선택 이유(3개_2)', '원하는 분반 번호(3개_3)', '분반 선택 이유(3개_3)', '유입경로', 'BDA를 알게된 인스타그램 콘텐츠', '콘텐츠를 보게 된 경로', '관심을 끌었던 인스타그램 콘텐츠', '관심이 없었던 인스타그램 콘텐츠', '등록 결정 이유(인스타그램)', '보고싶은 컨텐츠', 'whyBDA', '재등록 여부', '기존 분반[3기]', '기존 분반[4기]', '기존 분반[5기]', '기존 분반[6기]', '기존 분반[7기]', '기존 분반[8기]', '기존 분반[9기]', '가장 만족한 활동(재등록)', '기대되는 활동(재등록)', '만족, 기대 답변 이유(재등록)', 'whyBDA(재등록)', '프로젝트 형태', '조별활동 희망', '투입 가능 시간', '얻고자 하는 것', 'job_domain', 'company', '직업 형태(현재직장)', '근무 연차(현재직장)', 'whyBDA(현재직장)', '데이터 분석 역량 필요 이유(현재직장)', '직장 도메인(이전직장)', '직업명(이전직장)', '근무 연차(이전직장)', '데이터 분석 역량 필요 이유(이전직장)', '희망 진로', '희망 도메인', '희망 직무', '희망 직무 데이터 역량', '관심있는 기업명', '언어 숙련도(SQL)', '언어 숙련도(Python)', '언어 숙련도(R)', '패키지 숙련도(Pandas)', '패키지 숙련도(Numpy)', '패키지 숙련도(Scikit-learn)', '패키지 숙련도(Pytorch)', '패키지 숙련도(TensorFlow)', '패키지 숙련도(Keras)', '시각화 도구 숙련도(Looker Studio)', '시각화 도구 숙련도(Tableau)', '시각화 도구 숙련도(Power BI)', '시각화 도구 숙련도(Python 시각화 라이브러리)', '취득 자격증', '취득 희망 자격증', '희망 자격증 스터디 기간', '데이터 관련 활동 경험(스터디)', '데이터 관련 활동 경험(동아리)', '데이터 관련 활동 경험(학회)', '아쉬웠던 점(활동 중)', '데이터 관련 대회 경험(공모전)', '데이터 관련 대회 경험(프로젝트)', '아쉬웠던 점', '관심있는 채용 프로그램', '그 밖의 채용 프로그램', '원데이 클래스 주제', '원데이 클래스 강의 형식', '원데이 클래스 난이도', '원데이 클래스 참여할 의향', '원데이 클래스 요청 사항', 'BDA WAVE 추가 컨텐츠', '학술제 참여 의사', '학술제 컨텐츠', '데이터 외 희망 직무', '원하는 현직자 수준', '원하는 현직자 강의 주제', '현직자 기업 수준', '현직자 강의 형식', '현직자 강의 규모', '규모 선택 이유(현직자)', '데이터 분석 대회 경험', '공모전 성능 향상 방법', '아이디어 공모전 기획 방법', '공모전 수상 경력', '원하는 행사(공멘토)', 'whyBDA(공멘토)', '응답폼유무']

In [ ]:
# 응답폼이 없는 사람 필터링
응답폼_없는_사람 = df[df['응답폼유무'] == False]

# 결과 출력
print(응답폼_없는_사람)

     이름_x                       이메일_x      전화번호_x             소속대학      식별자  \
8     강민지      aperitif0105@gmail.com  1024105276              NaN   강민지_52
13    강연우    kangyunwoo0716@gmail.com  1068025985              NaN   강연우_59
24    강혜린     kang1019k@hanyang.ac.kr  1043183773              NaN   강혜린_37
31    고준섭          ko911@hallym.ac.kr  1068186366              NaN   고준섭_63
43    구서영           sy2328@g.skku.edu  1040626751              NaN   구서영_67
62    김가은      32200310@dankook.ac.kr  1026155807              NaN   김가은_58
78   김나영             yeoh89@mju.ac.kr  1087324573     명지대학교 자연캠퍼스   김나영 _45
147   김세희  shinetheworld112@gmail.com  1047419493              NaN   김세희_94
159   김수현         sh1121404@khu.ac.kr  1059563154              NaN   김수현_31
170   김예리          yeri1567@gmail.com  1066021567              NaN   김예리_15
206   김주경           kjook87@gmail.com  1090198452              NaN   김주경_84
208   김지민          zimni205@gmail.com  1099384383              NaN   김지민_43
229   김태영        gundamty@korea.ac.kr  1073289555              NaN   김태영_95
281   문현욱        moonhw0404@gmail.com  1042075121              NaN   문현욱_51
298    박샘       barksam0917@gmail.com  1058081569              NaN    박샘_15
333  박정인   jiparkpretty3131@gmail.com  1093240637     한신대학교 오산캠퍼스   박정인 _06
350   박찬규          usck1021@naver.com  1092376959              NaN   박찬규_69
411  손연주         yjson04@yonsei.ac.kr  1047322697           연세대학교   손연주 _26
425   신미수         meemeu.57@gmail.com  1044487050              NaN   신미수_70
460   양지호          jiho2299@gmail.com  1055574726              NaN   양지호_47
482   오하영         gkduddlvk@khu.ac.kr  1041692150              NaN   오하영_21
521   유현선          hsyoo826@gmail.com  1036499431              NaN   유현선_94
537   윤예정         yyj285728@gmail.com  1054647304              NaN   윤예정_73
540   윤정원           gethlev@gmail.com  1039190959              NaN   윤정원_09
549   이가영          applelgy@gmail.com  1024134155              NaN   이가영_41
551  이건희        geonhee8604@gmail.com  1034408604  성균관대학교 인문과학캠퍼스   이건희 _86
555   이경진          oi236612@gmail.com  1099882352              NaN   이경진_23
608   이예나     2015300@sookmyung.ac.kr  1099372187              NaN   이예나_21
658   이주연      adminjy@soongsil.ac.kr  1049352552              NaN   이주연_25
677   이지은         jieun2867@gmail.com  1025572868              NaN   이지은_28
697   이현지         guswl4174@naver.com  1038184174              NaN   이현지_41
698   이형규          hglee717@gmail.com  1028376570              NaN   이형규_65
740  장혜인       01063347878j@gmail.com  1063347878           충남대학교   장혜인 _78
790   정지원  jeong_jiwon02@yonsei.ac.kr  1077379852              NaN   정지원_98
811   조소현   sohyeon0601@kyonggi.ac.kr  1085722285              NaN   조소현_22
824   주지현      a01025715218@gmail.com  1025715218          이화여자대학교   주지현_52
858   최은교         dmsry2469@gmail.com  1093122470              NaN   최은교_24
879   한상윤         danny0884@naver.com  1099010885              NaN   한상윤_08
888  한지훈       jameshan0308@gmail.com  1074536252      명지대학교 자연캠퍼스  한지훈 _62
909   황소윤      soyoon030619@gmail.com  1051202876              NaN   황소윤_28

       class1 class2  class3  class4 내/외국인  ... 현직자 강의 형식 현직자 강의 규모  \
8          14     15     NaN     NaN   NaN  ...       NaN       NaN
13     일반 학회원   None     NaN     NaN   NaN  ...       NaN       NaN
24          2   None     NaN     NaN   NaN  ...       NaN       NaN
31          2      8     NaN     NaN   NaN  ...       NaN       NaN
43          2      7     NaN     NaN   NaN  ...       NaN       NaN
62         14   None     NaN     NaN   NaN  ...       NaN       NaN
78     일반 학회원   None     NaN     NaN   NaN  ...       NaN       NaN
147        12     16     NaN     NaN   NaN  ...       NaN       NaN
159        14     15     NaN     NaN   NaN  ...       NaN       NaN
170        15   None     NaN     NaN   NaN  ...       NaN       NaN
206        14     16     NaN     NaN   NaN  ...       NaN       NaN
208         1      4     NaN     NaN   NaN  ...       NaN       NaN
229         2   None     NaN     NaN   NaN  ...       NaN       NaN
281         1   None     NaN     NaN   NaN  ...       NaN       NaN
298  공모전 멘토링반   None     NaN     NaN   NaN  ...       NaN       NaN
333         2   None     NaN     NaN   NaN  ...       NaN       NaN
350        15   None     NaN     NaN   NaN  ...       NaN       NaN
411         1      4     NaN     NaN   NaN  ...       NaN       NaN
425        12   None     NaN     NaN   NaN  ...       NaN       NaN
460        12     15     NaN     NaN   NaN  ...       NaN       NaN
482         1      2     NaN     NaN   NaN  ...       NaN       NaN
521         7   None     NaN     NaN   NaN  ...       NaN       NaN
537    일반 학회원   None     NaN     NaN   NaN  ...       NaN       NaN
540         1      5     NaN     NaN   NaN  ...       NaN       NaN
549        14     15     NaN     NaN   NaN  ...       NaN       NaN
551         2   None     NaN     NaN   NaN  ...       NaN       NaN
555        14   None     NaN     NaN   NaN  ...       NaN       NaN
608        16   None     NaN     NaN   NaN  ...       NaN       NaN
658         1      2     NaN     NaN   NaN  ...       NaN       NaN
677         7     12     NaN     NaN   NaN  ...       NaN       NaN
697        15   None     NaN     NaN   NaN  ...       NaN       NaN
698         7     15     NaN     NaN   NaN  ...       NaN       NaN
740         4   None     NaN     NaN   NaN  ...       NaN       NaN
790         2   None     NaN     NaN   NaN  ...       NaN       NaN
811         2   None     NaN     NaN   NaN  ...       NaN       NaN
824         6   None     NaN     NaN   NaN  ...       NaN       NaN
858         7     15     NaN     NaN   NaN  ...       NaN       NaN
879         2     12     NaN     NaN   NaN  ...       NaN       NaN
888         4   None     NaN     NaN   NaN  ...       NaN       NaN
909         6   None     NaN     NaN   NaN  ...       NaN       NaN

    규모 선택 이유(현직자) 데이터 분석 대회 경험 공모전 성능 향상 방법 아이디어 공모전 기획 방법 공모전 수상 경력  \
8             NaN          NaN          NaN            NaN       NaN
13            NaN          NaN          NaN            NaN       NaN
24            NaN          NaN          NaN            NaN       NaN
31            NaN          NaN          NaN            NaN       NaN
43            NaN          NaN          NaN            NaN       NaN
62            NaN          NaN          NaN            NaN       NaN
78            NaN          NaN          NaN            NaN       NaN
147           NaN          NaN          NaN            NaN       NaN
159           NaN          NaN          NaN            NaN       NaN
170           NaN          NaN          NaN            NaN       NaN
206           NaN          NaN          NaN            NaN       NaN
208           NaN          NaN          NaN            NaN       NaN
229           NaN          NaN          NaN            NaN       NaN
281           NaN          NaN          NaN            NaN       NaN
298           NaN          NaN          NaN            NaN       NaN
333           NaN          NaN          NaN            NaN       NaN
350           NaN          NaN          NaN            NaN       NaN
411           NaN          NaN          NaN            NaN       NaN
425           NaN          NaN          NaN            NaN       NaN
460           NaN          NaN          NaN            NaN       NaN
482           NaN          NaN          NaN            NaN       NaN
521           NaN          NaN          NaN            NaN       NaN
537           NaN          NaN          NaN            NaN       NaN
540           NaN          NaN          NaN            NaN       NaN
549           NaN          NaN          NaN            NaN       NaN
551           NaN          NaN          NaN            NaN       NaN
555           NaN          NaN          NaN            NaN       NaN
608           NaN          NaN          NaN            NaN       NaN
658           NaN          NaN          NaN            NaN       NaN
677           NaN          NaN          NaN            NaN       NaN
697           NaN          NaN          NaN            NaN       NaN
698           NaN          NaN          NaN            NaN       NaN
740           NaN          NaN          NaN            NaN       NaN
790           NaN          NaN          NaN            NaN       NaN
811           NaN          NaN          NaN            NaN       NaN
824           NaN          NaN          NaN            NaN       NaN
858           NaN          NaN          NaN            NaN       NaN
879           NaN          NaN          NaN            NaN       NaN
888           NaN          NaN          NaN            NaN       NaN
909           NaN          NaN          NaN            NaN       NaN

    원하는 행사(공멘토) whyBDA(공멘토)  응답폼유무
8           NaN         NaN  False
13          NaN         NaN  False
24          NaN         NaN  False
31          NaN         NaN  False
43          NaN         NaN  False
62          NaN         NaN  False
78          NaN         NaN  False
147         NaN         NaN  False
159         NaN         NaN  False
170         NaN         NaN  False
206         NaN         NaN  False
208         NaN         NaN  False
229         NaN         NaN  False
281         NaN         NaN  False
298         NaN         NaN  False
333         NaN         NaN  False
350         NaN         NaN  False
411         NaN         NaN  False
425         NaN         NaN  False
460         NaN         NaN  False
482         NaN         NaN  False
521         NaN         NaN  False
537         NaN         NaN  False
540         NaN         NaN  False
549         NaN         NaN  False
551         NaN         NaN  False
555         NaN         NaN  False
608         NaN         NaN  False
658         NaN         NaN  False
677         NaN         NaN  False
697         NaN         NaN  False
698         NaN         NaN  False
740         NaN         NaN  False
790         NaN         NaN  False
811         NaN         NaN  False
824         NaN         NaN  False
858         NaN         NaN  False
879         NaN         NaN  False
888         NaN         NaN  False
909         NaN         NaN  False

[40 rows x 133 columns]

In [ ]:
# 최종 컬럼 확인
print(df.columns.tolist())

['이름_x', '이메일_x', '전화번호_x', '소속대학', '식별자', 'class1', 'class2', 'class3', 'class4', '내/외국인', '성별', 'birthday', '거주지', '세부 거주지', '직업', '이름_y', '전화번호_y', '이메일_y', '최종학력', '재학 여부(석사)', 'school2', '단과 대학(석사)', 'major2', '재학 여부(학사)', '휴학 이유', '이수학기', '수강학점', 'school1', '단과 대학(학사)', 'major1_1', 'major type', 'major1_2', 'major1_3', '원하는 분반 개수', '원하는 활동(일반)', '원하는 분반 번호(1개)', '분반 선택 이유(1개)', '원하는 분반 번호(2개_1)', '분반 선택 이유(2개_1)', '원하는 분반 번호(2개_2)', '분반 선택 이유(2개_2)', '원하는 분반 번호(3개_1)', '분반 선택 이유(3개_1)', '원하는 분반 번호(3개_2)', '분반 선택 이유(3개_2)', '원하는 분반 번호(3개_3)', '분반 선택 이유(3개_3)', '유입경로', 'BDA를 알게된 인스타그램 콘텐츠', '콘텐츠를 보게 된 경로', '관심을 끌었던 인스타그램 콘텐츠', '관심이 없었던 인스타그램 콘텐츠', '등록 결정 이유(인스타그램)', '보고싶은 컨텐츠', 'whyBDA', '재등록 여부', '기존 분반[3기]', '기존 분반[4기]', '기존 분반[5기]', '기존 분반[6기]', '기존 분반[7기]', '기존 분반[8기]', '기존 분반[9기]', '가장 만족한 활동(재등록)', '기대되는 활동(재등록)', '만족, 기대 답변 이유(재등록)', 'whyBDA(재등록)', '프로젝트 형태', '조별활동 희망', '투입 가능 시간', '얻고자 하는 것', 'job_domain', 'company', '직업 형태(현재직장)', '근무 연차(현재직장)', 'whyBDA(현재직장)', '데이터 분석 역량 필요 이유(현재직장)', '직장 도메인(이전직장)', '직업명(이전직장)', '근무 연차(이전직장)', '데이터 분석 역량 필요 이유(이전직장)', '희망 진로', '희망 도메인', '희망 직무', '희망 직무 데이터 역량', '관심있는 기업명', '언어 숙련도(SQL)', '언어 숙련도(Python)', '언어 숙련도(R)', '패키지 숙련도(Pandas)', '패키지 숙련도(Numpy)', '패키지 숙련도(Scikit-learn)', '패키지 숙련도(Pytorch)', '패키지 숙련도(TensorFlow)', '패키지 숙련도(Keras)', '시각화 도구 숙련도(Looker Studio)', '시각화 도구 숙련도(Tableau)', '시각화 도구 숙련도(Power BI)', '시각화 도구 숙련도(Python 시각화 라이브러리)', '취득 자격증', '취득 희망 자격증', '희망 자격증 스터디 기간', '데이터 관련 활동 경험(스터디)', '데이터 관련 활동 경험(동아리)', '데이터 관련 활동 경험(학회)', '아쉬웠던 점(활동 중)', '데이터 관련 대회 경험(공모전)', '데이터 관련 대회 경험(프로젝트)', '아쉬웠던 점', '관심있는 채용 프로그램', '그 밖의 채용 프로그램', '원데이 클래스 주제', '원데이 클래스 강의 형식', '원데이 클래스 난이도', '원데이 클래스 참여할 의향', '원데이 클래스 요청 사항', 'BDA WAVE 추가 컨텐츠', '학술제 참여 의사', '학술제 컨텐츠', '데이터 외 희망 직무', '원하는 현직자 수준', '원하는 현직자 강의 주제', '현직자 기업 수준', '현직자 강의 형식', '현직자 강의 규모', '규모 선택 이유(현직자)', '데이터 분석 대회 경험', '공모전 성능 향상 방법', '아이디어 공모전 기획 방법', '공모전 수상 경력', '원하는 행사(공멘토)', 'whyBDA(공멘토)', '응답폼유무']

In [ ]:
major_list = ['컴퓨터', '인공지능', 'AI', '소프트웨어', '데이터', '통계', '산업경영', '산업']
df.loc[:, "major_data"] = df['major1_1'].fillna('').apply(lambda x: any(major in x for major in major_list))

In [ ]:
print(df['응답폼유무'].value_counts())

응답폼유무
True     878
False     40
Name: count, dtype: int64

In [ ]:
df[df['응답폼유무'] == False]

,이름_x,이메일_x,전화번호_x,소속대학,식별자,class1,class2,class3,class4,내/외국인,...,현직자 강의 규모,규모 선택 이유(현직자),데이터 분석 대회 경험,공모전 성능 향상 방법,아이디어 공모전 기획 방법,공모전 수상 경력,원하는 행사(공멘토),whyBDA(공멘토),응답폼유무,major_data
8,강민지,aperitif0105@gmail.com,1024105276,NaN,강민지_52,14,15,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
13,강연우,kangyunwoo0716@gmail.com,1068025985,NaN,강연우_59,일반 학회원,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
24,강혜린,kang1019k@hanyang.ac.kr,1043183773,NaN,강혜린_37,2,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
31,고준섭,ko911@hallym.ac.kr,1068186366,NaN,고준섭_63,2,8,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
43,구서영,sy2328@g.skku.edu,1040626751,NaN,구서영_67,2,7,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
62,김가은,32200310@dankook.ac.kr,1026155807,NaN,김가은_58,14,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
78,김나영,yeoh89@mju.ac.kr,1087324573,명지대학교 자연캠퍼스,김나영 _45,일반 학회원,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
147,김세희,shinetheworld112@gmail.com,1047419493,NaN,김세희_94,12,16,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
159,김수현,sh1121404@khu.ac.kr,1059563154,NaN,김수현_31,14,15,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
170,김예리,yeri1567@gmail.com,1066021567,NaN,김예리_15,15,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
206,김주경,kjook87@gmail.com,1090198452,NaN,김주경_84,14,16,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
208,김지민,zimni205@gmail.com,1099384383,NaN,김지민_43,1,4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
229,김태영,gundamty@korea.ac.kr,1073289555,NaN,김태영_95,2,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
281,문현욱,moonhw0404@gmail.com,1042075121,NaN,문현욱_51,1,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
298,박샘,barksam0917@gmail.com,1058081569,NaN,박샘_15,공모전 멘토링반,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
333,박정인,jiparkpretty3131@gmail.com,1093240637,한신대학교 오산캠퍼스,박정인 _06,2,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
350,박찬규,usck1021@naver.com,1092376959,NaN,박찬규_69,15,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
411,손연주,yjson04@yonsei.ac.kr,1047322697,연세대학교,손연주 _26,1,4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
425,신미수,meemeu.57@gmail.com,1044487050,NaN,신미수_70,12,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
460,양지호,jiho2299@gmail.com,1055574726,NaN,양지호_47,12,15,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
482,오하영,gkduddlvk@khu.ac.kr,1041692150,NaN,오하영_21,1,2,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
521,유현선,hsyoo826@gmail.com,1036499431,NaN,유현선_94,7,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
537,윤예정,yyj285728@gmail.com,1054647304,NaN,윤예정_73,일반 학회원,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
540,윤정원,gethlev@gmail.com,1039190959,NaN,윤정원_09,1,5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
549,이가영,applelgy@gmail.com,1024134155,NaN,이가영_41,14,15,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
551,이건희,geonhee8604@gmail.com,1034408604,성균관대학교 인문과학캠퍼스,이건희 _86,2,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
555,이경진,oi236612@gmail.com,1099882352,NaN,이경진_23,14,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
608,이예나,2015300@sookmyung.ac.kr,1099372187,NaN,이예나_21,16,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
658,이주연,adminjy@soongsil.ac.kr,1049352552,NaN,이주연_25,1,2,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
677,이지은,jieun2867@gmail.com,1025572868,NaN,이지은_28,7,12,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
697,이현지,guswl4174@naver.com,1038184174,NaN,이현지_41,15,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
698,이형규,hglee717@gmail.com,1028376570,NaN,이형규_65,7,15,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
740,장혜인,01063347878j@gmail.com,1063347878,충남대학교,장혜인 _78,4,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
790,정지원,jeong_jiwon02@yonsei.ac.kr,1077379852,NaN,정지원_98,2,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
811,조소현,sohyeon0601@kyonggi.ac.kr,1085722285,NaN,조소현_22,2,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
824,주지현,a01025715218@gmail.com,1025715218,이화여자대학교,주지현_52,6,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
858,최은교,dmsry2469@gmail.com,1093122470,NaN,최은교_24,7,15,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
879,한상윤,danny0884@naver.com,1099010885,NaN,한상윤_08,2,12,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
888,한지훈,jameshan0308@gmail.com,1074536252,명지대학교 자연캠퍼스,한지훈 _62,4,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
909,황소윤,soyoon030619@gmail.com,1051202876,NaN,황소윤_28,6,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False

In [ ]:
print(f"중복 제거 후 행 갯수: {len(df)}")

중복 제거 후 행 갯수: 918

In [ ]:
print(df.columns.tolist())  # 컬럼 확인

['이름_x', '이메일_x', '전화번호_x', '소속대학', '식별자', 'class1', 'class2', 'class3', 'class4', '내/외국인', '성별', 'birthday', '거주지', '세부 거주지', '직업', '이름_y', '전화번호_y', '이메일_y', '최종학력', '재학 여부(석사)', 'school2', '단과 대학(석사)', 'major2', '재학 여부(학사)', '휴학 이유', '이수학기', '수강학점', 'school1', '단과 대학(학사)', 'major1_1', 'major type', 'major1_2', 'major1_3', '원하는 분반 개수', '원하는 활동(일반)', '원하는 분반 번호(1개)', '분반 선택 이유(1개)', '원하는 분반 번호(2개_1)', '분반 선택 이유(2개_1)', '원하는 분반 번호(2개_2)', '분반 선택 이유(2개_2)', '원하는 분반 번호(3개_1)', '분반 선택 이유(3개_1)', '원하는 분반 번호(3개_2)', '분반 선택 이유(3개_2)', '원하는 분반 번호(3개_3)', '분반 선택 이유(3개_3)', '유입경로', 'BDA를 알게된 인스타그램 콘텐츠', '콘텐츠를 보게 된 경로', '관심을 끌었던 인스타그램 콘텐츠', '관심이 없었던 인스타그램 콘텐츠', '등록 결정 이유(인스타그램)', '보고싶은 컨텐츠', 'whyBDA', '재등록 여부', '기존 분반[3기]', '기존 분반[4기]', '기존 분반[5기]', '기존 분반[6기]', '기존 분반[7기]', '기존 분반[8기]', '기존 분반[9기]', '가장 만족한 활동(재등록)', '기대되는 활동(재등록)', '만족, 기대 답변 이유(재등록)', 'whyBDA(재등록)', '프로젝트 형태', '조별활동 희망', '투입 가능 시간', '얻고자 하는 것', 'job_domain', 'company', '직업 형태(현재직장)', '근무 연차(현재직장)', 'whyBDA(현재직장)', '데이터 분석 역량 필요 이유(현재직장)', '직장 도메인(이전직장)', '직업명(이전직장)', '근무 연차(이전직장)', '데이터 분석 역량 필요 이유(이전직장)', '희망 진로', '희망 도메인', '희망 직무', '희망 직무 데이터 역량', '관심있는 기업명', '언어 숙련도(SQL)', '언어 숙련도(Python)', '언어 숙련도(R)', '패키지 숙련도(Pandas)', '패키지 숙련도(Numpy)', '패키지 숙련도(Scikit-learn)', '패키지 숙련도(Pytorch)', '패키지 숙련도(TensorFlow)', '패키지 숙련도(Keras)', '시각화 도구 숙련도(Looker Studio)', '시각화 도구 숙련도(Tableau)', '시각화 도구 숙련도(Power BI)', '시각화 도구 숙련도(Python 시각화 라이브러리)', '취득 자격증', '취득 희망 자격증', '희망 자격증 스터디 기간', '데이터 관련 활동 경험(스터디)', '데이터 관련 활동 경험(동아리)', '데이터 관련 활동 경험(학회)', '아쉬웠던 점(활동 중)', '데이터 관련 대회 경험(공모전)', '데이터 관련 대회 경험(프로젝트)', '아쉬웠던 점', '관심있는 채용 프로그램', '그 밖의 채용 프로그램', '원데이 클래스 주제', '원데이 클래스 강의 형식', '원데이 클래스 난이도', '원데이 클래스 참여할 의향', '원데이 클래스 요청 사항', 'BDA WAVE 추가 컨텐츠', '학술제 참여 의사', '학술제 컨텐츠', '데이터 외 희망 직무', '원하는 현직자 수준', '원하는 현직자 강의 주제', '현직자 기업 수준', '현직자 강의 형식', '현직자 강의 규모', '규모 선택 이유(현직자)', '데이터 분석 대회 경험', '공모전 성능 향상 방법', '아이디어 공모전 기획 방법', '공모전 수상 경력', '원하는 행사(공멘토)', 'whyBDA(공멘토)', '응답폼유무', 'major_data']

In [ ]:
file_path = '/content/drive/MyDrive/BDA 6기 운영진/6기 데이터팀/김지민/staff.xlsx'


운영진 = pd.read_excel(file_path, dtype={'phone_number': str})

In [ ]:
운영진['staff_name'] = 운영진['staff_name'].str.strip()

운영진['식별자'] = 운영진['staff_name'] + '_' + 운영진['phone_number'].astype(str).str[-4:-2]

In [ ]:
import pandas as pd

# 두 개의 DataFrame: df와 운영진

# df를 운영진의 '식별자' 열을 기준으로 병합 (update할 열만 선택)
df_updated = df.merge(운영진[['식별자', 'school1', 'major1_1', 'major1_2', 'major_data']],
                      on='식별자',
                      how='left',
                      suffixes=('', '_운영진'))
print(df_updated.columns.tolist())  # 컬럼 확인

['이름_x', '이메일_x', '전화번호_x', '소속대학', '식별자', 'class1', 'class2', 'class3', 'class4', '내/외국인', '성별', 'birthday', '거주지', '세부 거주지', '직업', '이름_y', '전화번호_y', '이메일_y', '최종학력', '재학 여부(석사)', 'school2', '단과 대학(석사)', 'major2', '재학 여부(학사)', '휴학 이유', '이수학기', '수강학점', 'school1', '단과 대학(학사)', 'major1_1', 'major type', 'major1_2', 'major1_3', '원하는 분반 개수', '원하는 활동(일반)', '원하는 분반 번호(1개)', '분반 선택 이유(1개)', '원하는 분반 번호(2개_1)', '분반 선택 이유(2개_1)', '원하는 분반 번호(2개_2)', '분반 선택 이유(2개_2)', '원하는 분반 번호(3개_1)', '분반 선택 이유(3개_1)', '원하는 분반 번호(3개_2)', '분반 선택 이유(3개_2)', '원하는 분반 번호(3개_3)', '분반 선택 이유(3개_3)', '유입경로', 'BDA를 알게된 인스타그램 콘텐츠', '콘텐츠를 보게 된 경로', '관심을 끌었던 인스타그램 콘텐츠', '관심이 없었던 인스타그램 콘텐츠', '등록 결정 이유(인스타그램)', '보고싶은 컨텐츠', 'whyBDA', '재등록 여부', '기존 분반[3기]', '기존 분반[4기]', '기존 분반[5기]', '기존 분반[6기]', '기존 분반[7기]', '기존 분반[8기]', '기존 분반[9기]', '가장 만족한 활동(재등록)', '기대되는 활동(재등록)', '만족, 기대 답변 이유(재등록)', 'whyBDA(재등록)', '프로젝트 형태', '조별활동 희망', '투입 가능 시간', '얻고자 하는 것', 'job_domain', 'company', '직업 형태(현재직장)', '근무 연차(현재직장)', 'whyBDA(현재직장)', '데이터 분석 역량 필요 이유(현재직장)', '직장 도메인(이전직장)', '직업명(이전직장)', '근무 연차(이전직장)', '데이터 분석 역량 필요 이유(이전직장)', '희망 진로', '희망 도메인', '희망 직무', '희망 직무 데이터 역량', '관심있는 기업명', '언어 숙련도(SQL)', '언어 숙련도(Python)', '언어 숙련도(R)', '패키지 숙련도(Pandas)', '패키지 숙련도(Numpy)', '패키지 숙련도(Scikit-learn)', '패키지 숙련도(Pytorch)', '패키지 숙련도(TensorFlow)', '패키지 숙련도(Keras)', '시각화 도구 숙련도(Looker Studio)', '시각화 도구 숙련도(Tableau)', '시각화 도구 숙련도(Power BI)', '시각화 도구 숙련도(Python 시각화 라이브러리)', '취득 자격증', '취득 희망 자격증', '희망 자격증 스터디 기간', '데이터 관련 활동 경험(스터디)', '데이터 관련 활동 경험(동아리)', '데이터 관련 활동 경험(학회)', '아쉬웠던 점(활동 중)', '데이터 관련 대회 경험(공모전)', '데이터 관련 대회 경험(프로젝트)', '아쉬웠던 점', '관심있는 채용 프로그램', '그 밖의 채용 프로그램', '원데이 클래스 주제', '원데이 클래스 강의 형식', '원데이 클래스 난이도', '원데이 클래스 참여할 의향', '원데이 클래스 요청 사항', 'BDA WAVE 추가 컨텐츠', '학술제 참여 의사', '학술제 컨텐츠', '데이터 외 희망 직무', '원하는 현직자 수준', '원하는 현직자 강의 주제', '현직자 기업 수준', '현직자 강의 형식', '현직자 강의 규모', '규모 선택 이유(현직자)', '데이터 분석 대회 경험', '공모전 성능 향상 방법', '아이디어 공모전 기획 방법', '공모전 수상 경력', '원하는 행사(공멘토)', 'whyBDA(공멘토)', '응답폼유무', 'major_data', 'school1_운영진', 'major1_1_운영진', 'major1_2_운영진', 'major_data_운영진']

In [ ]:
# 운영진 값으로 df의 값을 업데이트
df_updated['school1'] = df_updated['school1_운영진'].combine_first(df_updated['school1'])
df_updated['major1_1'] = df_updated['major1_1_운영진'].combine_first(df_updated['major1_1'])
df_updated['major1_2'] = df_updated['major1_2_운영진'].combine_first(df_updated['major1_2'])
df_updated['major_data'] = df_updated['major_data_운영진'].combine_first(df_updated['major_data'])

In [ ]:
print(df['major_data'].value_counts())

major_data
False    566
True     352
Name: count, dtype: int64

In [ ]:
df_updated[df_updated['응답폼유무'] == False]

,이름_x,이메일_x,전화번호_x,소속대학,식별자,class1,class2,class3,class4,내/외국인,...,아이디어 공모전 기획 방법,공모전 수상 경력,원하는 행사(공멘토),whyBDA(공멘토),응답폼유무,major_data,school1_운영진,major1_1_운영진,major1_2_운영진,major_data_운영진
8,강민지,aperitif0105@gmail.com,1024105276,NaN,강민지_52,14,15,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,경희대학교,NaN,경영학과,False
13,강연우,kangyunwoo0716@gmail.com,1068025985,NaN,강연우_59,일반 학회원,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,한국외국어대학교,국제금융학과,Business AI학과,False
24,강혜린,kang1019k@hanyang.ac.kr,1043183773,NaN,강혜린_37,2,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,한양대학교,실내건축디자인학과,데이터융합서비스디자인학과,NaN
31,고준섭,ko911@hallym.ac.kr,1068186366,NaN,고준섭_63,2,8,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,True,한림대학교,데이터테크학과,빅데이터전공,True
43,구서영,sy2328@g.skku.edu,1040626751,NaN,구서영_67,2,7,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,성균관대학교,문헌정보학과,경영학과,False
62,김가은,32200310@dankook.ac.kr,1026155807,NaN,김가은_58,14,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,단국대학교,수학과,정보통계학과,False
78,김나영,yeoh89@mju.ac.kr,1087324573,명지대학교 자연캠퍼스,김나영 _45,일반 학회원,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
147,김세희,shinetheworld112@gmail.com,1047419493,NaN,김세희_94,12,16,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,True,숙명여자대학교,IT공학전공,빅데이터분석학전공,True
159,김수현,sh1121404@khu.ac.kr,1059563154,NaN,김수현_31,14,15,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,경희대학교,원예생명공학,응용수학,False
170,김예리,yeri1567@gmail.com,1066021567,NaN,김예리_15,15,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,이화여자대학교,휴먼기계바이오공학부,NaN,False
206,김주경,kjook87@gmail.com,1090198452,NaN,김주경_84,14,16,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,가천대학교,경제학과,AI소프트웨어학부(인공지능전공),False
208,김지민,zimni205@gmail.com,1099384383,NaN,김지민_43,1,4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,True,명지대학교,응용소프트웨어학과,NaN,True
229,김태영,gundamty@korea.ac.kr,1073289555,NaN,김태영_95,2,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,고려대학교,사회학과,NaN,False
281,문현욱,moonhw0404@gmail.com,1042075121,NaN,문현욱_51,1,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,가천대학교,법학과,경영학과,False
298,박샘,barksam0917@gmail.com,1058081569,NaN,박샘_15,공모전 멘토링반,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
333,박정인,jiparkpretty3131@gmail.com,1093240637,한신대학교 오산캠퍼스,박정인 _06,2,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
350,박찬규,usck1021@naver.com,1092376959,NaN,박찬규_69,15,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,True,명지대학교,데이터테크놀로지학과,NaN,True
411,손연주,yjson04@yonsei.ac.kr,1047322697,연세대학교,손연주 _26,1,4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
425,신미수,meemeu.57@gmail.com,1044487050,NaN,신미수_70,12,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,동국대학교,사회학과,서베이앤데이터사이언스,False
460,양지호,jiho2299@gmail.com,1055574726,NaN,양지호_47,12,15,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,세종대학교,영어영문학과,비지니스애널리틱스 융합전공,False
482,오하영,gkduddlvk@khu.ac.kr,1041692150,NaN,오하영_21,1,2,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,경희대학교,문화관광콘텐츠학과,경영학과 (마이크로디그리 : AI 마이크로디그리),False
521,유현선,hsyoo826@gmail.com,1036499431,NaN,유현선_94,7,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,True,덕성여자대학교,디지털소프트웨어공학부,NaN,True
537,윤예정,yyj285728@gmail.com,1054647304,NaN,윤예정_73,일반 학회원,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,True,동국대학교,산업시스템공학과,데이터사이언스소프트웨어,True
540,윤정원,gethlev@gmail.com,1039190959,NaN,윤정원_09,1,5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,숙명여자대학교,데이터사이언스(석사),문화관광학과(학사),False
549,이가영,applelgy@gmail.com,1024134155,NaN,이가영_41,14,15,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,한국외국어대학교,포르투갈어학과,융복합소프트웨어,False
551,이건희,geonhee8604@gmail.com,1034408604,성균관대학교 인문과학캠퍼스,이건희 _86,2,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
555,이경진,oi236612@gmail.com,1099882352,NaN,이경진_23,14,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,True,이화여자대학교,통계학과,경영학과,True
608,이예나,2015300@sookmyung.ac.kr,1099372187,NaN,이예나_21,16,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,숙명여자대학교,수학과,빅데이터전공,False
658,이주연,adminjy@soongsil.ac.kr,1049352552,NaN,이주연_25,1,2,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,숭실대학교,행정학부,경영학부,False
677,이지은,jieun2867@gmail.com,1025572868,NaN,이지은_28,7,12,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,동국대학교,멀티미디어공학과,NaN,False
697,이현지,guswl4174@naver.com,1038184174,NaN,이현지_41,15,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,True,덕성여자대학교,IT미디어공학과,NaN,True
698,이형규,hglee717@gmail.com,1028376570,NaN,이형규_65,7,15,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,세종대학교,미디어커뮤니케이션학과,NaN,False
740,장혜인,01063347878j@gmail.com,1063347878,충남대학교,장혜인 _78,4,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
790,정지원,jeong_jiwon02@yonsei.ac.kr,1077379852,NaN,정지원_98,2,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,True,연세대학교,보건행정학,데이터사이언스학,True
811,조소현,sohyeon0601@kyonggi.ac.kr,1085722285,NaN,조소현_22,2,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,경기대학교,경영학전공,관광이벤트전공,False
824,주지현,a01025715218@gmail.com,1025715218,이화여자대학교,주지현_52,6,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
858,최은교,dmsry2469@gmail.com,1093122470,NaN,최은교_24,7,15,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,세종대학교,경영학과,비즈니스 애널리틱스,False
879,한상윤,danny0884@naver.com,1099010885,NaN,한상윤_08,2,12,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,True,한양대학교,산업공학과,NaN,True
888,한지훈,jameshan0308@gmail.com,1074536252,명지대학교 자연캠퍼스,한지훈 _62,4,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
909,황소윤,soyoon030619@gmail.com,1051202876,NaN,황소윤_28,6,None,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,False,경기대학교,경영정보학과,산업시스템공학,False

In [ ]:
df = df_updated.copy()

In [ ]:
jobdf = df[['재등록 여부', '직업', '이름_x', '이메일_x', '유입경로','최종학력','school1', '재학 여부(석사)', '재학 여부(학사)', 'job_domain', '희망 진로', '응답폼유무']]

In [ ]:
# 1️⃣ 대학생인데 최종학력이 고졸인 사람 찾기
students_to_fix = jobdf[(jobdf['직업'] == '대학생') & (jobdf['최종학력'] == '고등학교 졸업')]
print(" [최종학력 '고졸' → '대학교 학사'] 대상자 목록")
print(students_to_fix[['이름_x', '이메일_x', '직업', '최종학력']])  # 주요 컬럼 출력

 [최종학력 '고졸' → '대학교 학사'] 대상자 목록
                             이름_x                   이메일_x   직업     최종학력
0    Hannah Safiah Binti Saharani     h.safiahx@gmail.com  대학생  고등학교 졸업
9                             강민지     kkmmgg711@gmail.com  대학생  고등학교 졸업
18                            강채연  chaekang5529@gmail.com  대학생  고등학교 졸업
25                            강혜영  haeyoung6634@gmail.com  대학생  고등학교 졸업
35                            공리원   liwon040709@gmail.com  대학생  고등학교 졸업
..                            ...                     ...  ...      ...
860                           최장우    ymkism0414@gmail.com  대학생  고등학교 졸업
874                           하성주      dorimhsj@gmail.com  대학생  고등학교 졸업
890                           한해인    nieahnah@dongguk.edu  대학생  고등학교 졸업
898                           형수환    paulel2083@gmail.com  대학생  고등학교 졸업
901                           홍민기    mingihong1@cau.ac.kr  대학생  고등학교 졸업

[77 rows x 4 columns]

In [ ]:
# 최종학력을 '대학교 학사'로 변경
jobdf.loc[students_to_fix.index, '최종학력'] = '대학교 학사'

# 변경된 데이터 다시 출력
students_fixed = jobdf.loc[students_to_fix.index, ['이름_x', '이메일_x', '직업', '최종학력']]
print("\n🟢 [수정 후] '대학교 학사'로 변경된 목록")
print(students_fixed)

🟢 [수정 후] '대학교 학사'로 변경된 목록
                             이름_x                   이메일_x   직업    최종학력
0    Hannah Safiah Binti Saharani     h.safiahx@gmail.com  대학생  대학교 학사
9                             강민지     kkmmgg711@gmail.com  대학생  대학교 학사
18                            강채연  chaekang5529@gmail.com  대학생  대학교 학사
25                            강혜영  haeyoung6634@gmail.com  대학생  대학교 학사
35                            공리원   liwon040709@gmail.com  대학생  대학교 학사
..                            ...                     ...  ...     ...
860                           최장우    ymkism0414@gmail.com  대학생  대학교 학사
874                           하성주      dorimhsj@gmail.com  대학생  대학교 학사
890                           한해인    nieahnah@dongguk.edu  대학생  대학교 학사
898                           형수환    paulel2083@gmail.com  대학생  대학교 학사
901                           홍민기    mingihong1@cau.ac.kr  대학생  대학교 학사

[77 rows x 4 columns]

In [ ]:
# 2️⃣ 대학원생인데 최종학력이 학사인 사람 찾기
graduates_to_fix = jobdf[(jobdf['직업'] == '대학원생') & (jobdf['최종학력'] == '대학교 학사')]
print("\n [최종학력 '대학교 학사' → '대학교 석사 이상'] 대상자 목록")
print(graduates_to_fix[['이름_x', '이메일_x', '직업', '최종학력']])  # 주요 컬럼 출력

 [최종학력 '대학교 학사' → '대학교 석사 이상'] 대상자 목록
    이름_x                    이메일_x    직업    최종학력
416  송민엽     effortyobi@gmail.com  대학원생  대학교 학사
595  이승섭  leesamuel1007@gmail.com  대학원생  대학교 학사
878  하태훈  billy93949772@gmail.com  대학원생  대학교 학사

In [ ]:
# 해당 사람들의 최종학력을 '대학교 석사 이상'으로 변경
jobdf.loc[graduates_to_fix.index, '최종학력'] = '대학교 석사 이상'
# 변경된 데이터 다시 출력
graduates_fixed = jobdf.loc[graduates_to_fix.index, ['이름_x', '이메일_x', '직업', '최종학력']]
print("\n [수정 후] '대학교 석사 이상'으로 변경된 목록")
print(graduates_fixed)

 [수정 후] '대학교 석사 이상'으로 변경된 목록
    이름_x                    이메일_x    직업       최종학력
416  송민엽     effortyobi@gmail.com  대학원생  대학교 석사 이상
595  이승섭  leesamuel1007@gmail.com  대학원생  대학교 석사 이상
878  하태훈  billy93949772@gmail.com  대학원생  대학교 석사 이상

In [ ]:
df['최종학력'] = jobdf['최종학력']

In [ ]:
df.columns

Index(['이름_x', '이메일_x', '전화번호_x', '소속대학', '식별자', 'class1', 'class2', 'class3',
       'class4', '내/외국인',
       ...
       '아이디어 공모전 기획 방법', '공모전 수상 경력', '원하는 행사(공멘토)', 'whyBDA(공멘토)', '응답폼유무',
       'major_data', 'school1_운영진', 'major1_1_운영진', 'major1_2_운영진',
       'major_data_운영진'],
      dtype='object', length=138)

In [ ]:
df.drop(columns=['school1_운영진', 'major1_1_운영진', 'major1_2_운영진', 'major_data_운영진'], inplace = True)
df.drop(columns=['이메일_y', '전화번호_y', '이름_y'], inplace = True)

In [ ]:
# 전화번호_x를 문자열로 바꾸고, 앞에 0이 없다면 0을 붙임
df['전화번호_x'] = df['전화번호_x'].astype(str).apply(lambda x: x if x.startswith('0') else '0' + x)



# 확인
print(df['전화번호_x'].head())

0    01058631610
1    01073063668
2    01097694955
3    01085059745
4    01063197508
Name: 전화번호_x, dtype: object

In [ ]:
df.rename(columns={'이메일_x': '이메일', '전화번호_x': '전화번호', '이름_x': '이름'}, inplace=True)
df.columns

Index(['이름', '이메일', '전화번호', '소속대학', '식별자', 'class1', 'class2', 'class3',
       'class4', '내/외국인',
       ...
       '현직자 강의 규모', '규모 선택 이유(현직자)', '데이터 분석 대회 경험', '공모전 성능 향상 방법',
       '아이디어 공모전 기획 방법', '공모전 수상 경력', '원하는 행사(공멘토)', 'whyBDA(공멘토)', '응답폼유무',
       'major_data'],
      dtype='object', length=131)

In [ ]:
df

,이름,이메일,전화번호,소속대학,식별자,class1,class2,class3,class4,내/외국인,...,현직자 강의 규모,규모 선택 이유(현직자),데이터 분석 대회 경험,공모전 성능 향상 방법,아이디어 공모전 기획 방법,공모전 수상 경력,원하는 행사(공멘토),whyBDA(공멘토),응답폼유무,major_data
0,Hannah Safiah Binti Saharani,h.safiahx@gmail.com,01058631610,NaN,Hannah Safiah Binti Saharani_16,1,None,NaN,NaN,외국인,...,100명 이상의 리스너와 10명 이상의 현직자,많은 참가자 선호,NaN,NaN,NaN,NaN,NaN,NaN,True,False
1,Ngoc Vu (알렉스),alex.vnbn@gmail.com,01073063668,연세대학교 서울캠퍼스,Ngoc Vu (알렉스)_36,14,None,NaN,NaN,외국인,...,10명 내외의 강의 리스너와 1명의 현직자,인원이 적어야 집중할 수 있어서,NaN,NaN,NaN,NaN,NaN,NaN,True,False
2,Nur Izzatty Binti Mohamad Jamal,izzattyjamal28@gmail.com,01097694955,University Malaysia Sarawak 대학교,Nur Izzatty Binti Mohamad Jamal_49,1,None,NaN,NaN,외국인,...,100명 이상의 리스너와 10명 이상의 현직자,10명 이상의 현직자의 다양한 경험과 인사이트를 한 번에 들을 수 있어서 선택했습니다,NaN,NaN,NaN,NaN,NaN,NaN,True,False
3,강동운,rvescd@gmail.com,01085059745,가천대학교 글로벌캠퍼스,강동운_97,15,None,NaN,NaN,내국인,...,3~50명 내외의 강의 리스너와 1명의 현직자,다양한 질문과 답변을 얻을 수 있어사,NaN,NaN,NaN,NaN,NaN,NaN,True,True
4,강두원,danbean2013@gmail.com,01063197508,세종대학교,강두원_75,4,None,NaN,NaN,내국인,...,10명 내외의 강의 리스너와 1명의 현직자,인원이 적어야 원활한 질의응답이 가능할 것 같아서,NaN,NaN,NaN,NaN,NaN,NaN,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,황정민,hjm8625@hanyang.ac.kr,01092538625,한양대학교 서울캠퍼스,황정민_86,2,None,NaN,NaN,내국인,...,3~50명 내외의 강의 리스너와 1명의 현직자,1대 50 정도가 집중하기 적당한것 같다,NaN,NaN,NaN,NaN,NaN,NaN,True,False
914,황종서,jongseo9955@gmail.com,01099553477,연세대학교 신촌캠퍼스,황종서_34,4,None,NaN,NaN,내국인,...,100명 이상의 리스너와 10명 이상의 현직자,온라인이라면 인원이 많을수록 좋을 것 같습니다,NaN,NaN,NaN,NaN,NaN,NaN,True,False
915,황준영,junyh29@gmail.com,01036658637,중앙대학교 서울캠퍼스,황준영_86,4,16,NaN,NaN,내국인,...,100명 이상의 리스너와 10명 이상의 현직자,여러명의 전문가에게 여러 시선에 대해 듣고 싶어서,NaN,NaN,NaN,NaN,NaN,NaN,True,False
916,황지영,jihwangww@gmail.com,01050552321,경북대학교 대구캠퍼스,황지영_23,4,5,NaN,NaN,내국인,...,3~50명 내외의 강의 리스너와 1명의 현직자,소규모는 너무 적고 적당한 규모의 인원이 있어야 집중할 수 있어서 & 질문하기 편함,NaN,NaN,NaN,NaN,NaN,NaN,True,True
917,황지희,ghkdwlgml0825@gmail.com,01062687360,연세대학교,황지희_73,12,15,NaN,NaN,내국인,...,100명 이상의 리스너와 10명 이상의 현직자,더 많은 현직자 분들을 뵙고 싶습니다.,NaN,NaN,NaN,NaN,NaN,NaN,True,False

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report

import pandas as pd

tdf = pd.read_excel('/content/drive/MyDrive/BDA 6기 운영진/6기 데이터팀/김지민/8_9_df.xlsx')
X = tdf['대학명(학사)']
y = tdf['대학명(학사)_최종']

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier

# TF-IDF로 텍스트를 숫자로 변환
vectorizer = TfidfVectorizer(max_features=5000, min_df=5, max_df=0.7)
X_vectorized = vectorizer.fit_transform(X)
#train, test 분리
X_train, X_test, y_train, y_test = train_test_split(X_vectorized,y, test_size = 0.3, random_state = 111)

from imblearn.combine import SMOTETomek
from imblearn.over_sampling import SMOTE

smote_tomek = SMOTETomek(random_state=111, smote=SMOTE(sampling_strategy='minority', k_neighbors=1))
X_resampled, y_resampled = smote_tomek.fit_resample(X_train, y_train)

from sklearn.svm import SVC
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

model = SVC(probability=True)

# 하이퍼파라미터 탐색 범위 설정
param_dist = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto'],
    'class_weight': ['balanced']
}

# RandomizedSearchCV로 최적의 하이퍼파라미터 탐색
random_search = RandomizedSearchCV(model, param_distributions=param_dist, n_iter=10, cv=3, random_state=111)
random_search.fit(X_train, y_train)

# 최적의 하이퍼파라미터로 모델 재훈련
best_model = random_search.best_estimator_
best_model.fit(X_train, y_train)

# 예측
y_pred = best_model.predict(X_test)
y_pred_prob = best_model.predict_proba(X_test)[:, 1]

# 성능 평가
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')  # 'weighted'로 설정
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-Score: {f1}")

Accuracy: 0.9908906882591093
Precision: 0.9925926595334491
Recall: 0.9908906882591093
F1-Score: 0.9906854767974411

In [ ]:
df['school1'] = df['school1'].fillna('정보없음')
df['school1최종'] = '학교'

In [ ]:
import pickle

# TfidfVectorizer 객체와 모델 저장
with open('vectorizer.pkl', 'wb') as f:
    pickle.dump(vectorizer, f)

with open('best_model.pkl', 'wb') as f:
    pickle.dump(best_model, f)

In [ ]:
import pickle

with open('vectorizer.pkl', 'rb') as f:
    vectorizer = pickle.load(f)

with open('best_model.pkl', 'rb') as f:
    best_model = pickle.load(f)

X = df['school1']
X_vectorized = vectorizer.transform(X)


df['school1최종'] = best_model.predict(X_vectorized)
print(df[['school1', 'school1최종']].head())

                           school1 school1최종
0                             정보없음      정보없음
1                      연세대학교 서울캠퍼스  연세대학교 본교
2  University Malaysia Sarawak 대학교   이화여자대학교
3                     가천대학교 글로벌캠퍼스     가천대학교
4                            세종대학교     세종대학교

In [ ]:
df['school2'] = df['school2'].fillna('정보없음')
df['school2최종'] = '학교'

In [ ]:
import pickle

# TfidfVectorizer 객체와 모델 저장
with open('vectorizer.pkl', 'wb') as f:
    pickle.dump(vectorizer, f)

with open('best_model.pkl', 'wb') as f:
    pickle.dump(best_model, f)

In [ ]:
import pickle

with open('vectorizer.pkl', 'rb') as f:
    vectorizer = pickle.load(f)

with open('best_model.pkl', 'rb') as f:
    best_model = pickle.load(f)

X = df['school2']
X_vectorized = vectorizer.transform(X)


df['school2최종'] = best_model.predict(X_vectorized)
print(df[['school2', 'school2최종']].head())

       school2 school2최종
0         정보없음      정보없음
1         정보없음      정보없음
2  연세대학교 국제캠퍼스  연세대학교 본교
3         정보없음      정보없음
4         정보없음      정보없음

In [ ]:
col = df.columns.tolist()

In [ ]:
# 출력할 최대 컬럼 수를 무한대로 설정
pd.set_option('display.max_columns', None)

# 컬럼 전체 출력
print(df.columns.tolist())

['이름', '이메일', '전화번호', '소속대학', '식별자', 'class1', 'class2', 'class3', 'class4', '내/외국인', '성별', 'birthday', '거주지', '세부 거주지', '직업', '최종학력', '재학 여부(석사)', 'school2', '단과 대학(석사)', 'major2', '재학 여부(학사)', '휴학 이유', '이수학기', '수강학점', 'school1', '단과 대학(학사)', 'major1_1', 'major type', 'major1_2', 'major1_3', '원하는 분반 개수', '원하는 활동(일반)', '원하는 분반 번호(1개)', '분반 선택 이유(1개)', '원하는 분반 번호(2개_1)', '분반 선택 이유(2개_1)', '원하는 분반 번호(2개_2)', '분반 선택 이유(2개_2)', '원하는 분반 번호(3개_1)', '분반 선택 이유(3개_1)', '원하는 분반 번호(3개_2)', '분반 선택 이유(3개_2)', '원하는 분반 번호(3개_3)', '분반 선택 이유(3개_3)', '유입경로', 'BDA를 알게된 인스타그램 콘텐츠', '콘텐츠를 보게 된 경로', '관심을 끌었던 인스타그램 콘텐츠', '관심이 없었던 인스타그램 콘텐츠', '등록 결정 이유(인스타그램)', '보고싶은 컨텐츠', 'whyBDA', '재등록 여부', '기존 분반[3기]', '기존 분반[4기]', '기존 분반[5기]', '기존 분반[6기]', '기존 분반[7기]', '기존 분반[8기]', '기존 분반[9기]', '가장 만족한 활동(재등록)', '기대되는 활동(재등록)', '만족, 기대 답변 이유(재등록)', 'whyBDA(재등록)', '프로젝트 형태', '조별활동 희망', '투입 가능 시간', '얻고자 하는 것', 'job_domain', 'company', '직업 형태(현재직장)', '근무 연차(현재직장)', 'whyBDA(현재직장)', '데이터 분석 역량 필요 이유(현재직장)', '직장 도메인(이전직장)', '직업명(이전직장)', '근무 연차(이전직장)', '데이터 분석 역량 필요 이유(이전직장)', '희망 진로', '희망 도메인', '희망 직무', '희망 직무 데이터 역량', '관심있는 기업명', '언어 숙련도(SQL)', '언어 숙련도(Python)', '언어 숙련도(R)', '패키지 숙련도(Pandas)', '패키지 숙련도(Numpy)', '패키지 숙련도(Scikit-learn)', '패키지 숙련도(Pytorch)', '패키지 숙련도(TensorFlow)', '패키지 숙련도(Keras)', '시각화 도구 숙련도(Looker Studio)', '시각화 도구 숙련도(Tableau)', '시각화 도구 숙련도(Power BI)', '시각화 도구 숙련도(Python 시각화 라이브러리)', '취득 자격증', '취득 희망 자격증', '희망 자격증 스터디 기간', '데이터 관련 활동 경험(스터디)', '데이터 관련 활동 경험(동아리)', '데이터 관련 활동 경험(학회)', '아쉬웠던 점(활동 중)', '데이터 관련 대회 경험(공모전)', '데이터 관련 대회 경험(프로젝트)', '아쉬웠던 점', '관심있는 채용 프로그램', '그 밖의 채용 프로그램', '원데이 클래스 주제', '원데이 클래스 강의 형식', '원데이 클래스 난이도', '원데이 클래스 참여할 의향', '원데이 클래스 요청 사항', 'BDA WAVE 추가 컨텐츠', '학술제 참여 의사', '학술제 컨텐츠', '데이터 외 희망 직무', '원하는 현직자 수준', '원하는 현직자 강의 주제', '현직자 기업 수준', '현직자 강의 형식', '현직자 강의 규모', '규모 선택 이유(현직자)', '데이터 분석 대회 경험', '공모전 성능 향상 방법', '아이디어 공모전 기획 방법', '공모전 수상 경력', '원하는 행사(공멘토)', 'whyBDA(공멘토)', '응답폼유무', 'major_data', 'school1최종', 'school2최종']

In [ ]:
df = df.rename(columns={
    '이름': 'member_name',
    '전화번호': 'phone_number',
    '이메일': 'email',
    '직업': 'job',
    '아쉬웠던 점(활동 중)' : '아쉬웠던 점(스터디, 동아리, 학회)',
    '아쉬웠던 점' : '아쉬웠던 점(공모전, 프로젝트)',
    '단과 대학(학사)': '전공계열'
})

In [ ]:
# 10기 응답 원본에만 있을 법한 컬럼 몇 개로 확인해보기
check_cols = ['세부 거주지', 'BDA를 알게된 인스타그램 콘텐츠', 'whyBDA(공멘토)', '원데이 클래스 난이도']

print(" 현재 df에 10기 고유 컬럼 포함 여부:")
for col in check_cols:
    print(f"{col}: {'✅ 있음' if col in df.columns else ' 없음'}")

 현재 df에 10기 고유 컬럼 포함 여부:
세부 거주지: ✅ 있음
BDA를 알게된 인스타그램 콘텐츠: ✅ 있음
whyBDA(공멘토): ✅ 있음
원데이 클래스 난이도: ✅ 있음

In [ ]:
df = df[['member_name',
 'email',
 'phone_number',
 'school1', 'school1최종',
 '식별자',
 'class1',
 'class2',
 'class3',
 'class4',
 '재등록 여부',
 '유입경로',
 'BDA를 알게된 인스타그램 콘텐츠',
 '콘텐츠를 보게 된 경로',
 '관심을 끌었던 인스타그램 콘텐츠',
 '관심이 없었던 인스타그램 콘텐츠',
 '등록 결정 이유(인스타그램)',
 '보고싶은 컨텐츠',
 'whyBDA',
 '재등록 여부',
 '기존 분반[3기]',
 '기존 분반[4기]',
 '기존 분반[5기]',
 '기존 분반[6기]',
 '기존 분반[7기]',
 '기존 분반[8기]',
 '기존 분반[9기]',
 '가장 만족한 활동(재등록)',
 '기대되는 활동(재등록)',
 '만족, 기대 답변 이유(재등록)',
 'whyBDA(재등록)',
 '내/외국인',
 '성별',
 'birthday',
 '거주지',
 '세부 거주지',
 '원하는 분반 개수',
 '원하는 활동(일반)',
 '원하는 분반 번호(1개)',
 '분반 선택 이유(1개)',
 '원하는 분반 번호(2개_1)',
 '분반 선택 이유(2개_1)',
 '원하는 분반 번호(2개_2)',
 '분반 선택 이유(2개_2)',
 '원하는 분반 번호(3개_1)',
 '분반 선택 이유(3개_1)',
 '원하는 분반 번호(3개_2)',
 '분반 선택 이유(3개_2)',
 '원하는 분반 번호(3개_3)',
 '분반 선택 이유(3개_3)',
 '프로젝트 형태',
 '조별활동 희망',
 '투입 가능 시간',
 '얻고자 하는 것',
 '최종학력',
 '재학 여부(석사)',
 'school2', 'school2최종',
 '단과 대학(석사)',
 'major2',
 '재학 여부(학사)',
 '이수학기',
 '소속대학',
 'major1_1',
 'major type',
 '전공계열',
 'major1_2',
 'major1_3',  'major_data',
 'job', 'job_domain',
 'company',
 'whyBDA(현재직장)',
 '데이터 분석 역량 필요 이유(현재직장)',
 '직업 형태(현재직장)',
 '근무 연차(현재직장)',
 '직장 도메인(이전직장)',
 '직업명(이전직장)',
 '근무 연차(이전직장)',
 '데이터 분석 역량 필요 이유(이전직장)',
 '희망 진로',
 '희망 도메인',
 '희망 직무',
 '희망 직무 데이터 역량',
 '관심있는 기업명',
 '언어 숙련도(SQL)',
 '언어 숙련도(Python)',
 '언어 숙련도(R)',
 '패키지 숙련도(Pandas)',
 '패키지 숙련도(Numpy)',
 '패키지 숙련도(Scikit-learn)',
 '패키지 숙련도(Pytorch)',
 '패키지 숙련도(TensorFlow)',
 '패키지 숙련도(Keras)',
 '시각화 도구 숙련도(Looker Studio)',
 '시각화 도구 숙련도(Tableau)',
 '시각화 도구 숙련도(Power BI)',
 '시각화 도구 숙련도(Python 시각화 라이브러리)',
 '취득 자격증',
 '취득 희망 자격증',
 '희망 자격증 스터디 기간',
 '데이터 관련 활동 경험(스터디)',
 '데이터 관련 활동 경험(동아리)',
 '데이터 관련 활동 경험(학회)',
 '아쉬웠던 점(스터디, 동아리, 학회)',
 '데이터 관련 대회 경험(공모전)',
 '데이터 관련 대회 경험(프로젝트)',
 '아쉬웠던 점(공모전, 프로젝트)',
 '관심있는 채용 프로그램',
 '그 밖의 채용 프로그램',
 '원데이 클래스 주제',
 '원데이 클래스 강의 형식',
 '원데이 클래스 난이도',
 '원데이 클래스 참여할 의향',
 '원데이 클래스 요청 사항',
 'BDA WAVE 추가 컨텐츠',
 '학술제 참여 의사',
 '학술제 컨텐츠',
 '데이터 외 희망 직무',
 '원하는 현직자 수준',
 '원하는 현직자 강의 주제',
 '현직자 기업 수준',
 '현직자 강의 형식',
 '현직자 강의 규모',
 '규모 선택 이유(현직자)',
 '데이터 분석 대회 경험',
 '공모전 성능 향상 방법',
 '아이디어 공모전 기획 방법',
 '공모전 수상 경력',
 '원하는 행사(공멘토)',
 'whyBDA(공멘토)',
 '응답폼유무'
 ]]

In [ ]:
df.to_excel('10기 학교처리용.xlsx', index=False)

In [ ]:
df = pd.read_excel('10기 학교처리용.xlsx', dtype = {'phone_number' : str, 'birthday' : str})

In [ ]:
df['marketing_agree'] = True
df['contents_agree'] = True
df['before_id'] = np.nan
df['generation'] = 10
df['withdrawal'] = False

df = df.sort_values(by = 'member_name')
# 새로운 member_id 생성
df = df.reset_index(drop=True)  # 인덱스를 재설정
df['member_id'] = '202510' + (df.index + 1).astype(str).str.zfill(4)

In [ ]:
findf = df[['member_id', 'member_name', 'generation', 'birthday', 'email',
       'phone_number', 'school1', 'major1_1', 'major1_2', 'major1_3',
       'school2', 'major2', 'job', 'job_domain','company',
       'major_data','class1', 'class2', 'class3', 'class4','marketing_agree', 'contents_agree', 'before_id', 'withdrawal', '식별자']]

In [ ]:
findf.to_excel('10기db.xlsx',index=False)

In [ ]:
col = df.columns.tolist()

In [ ]:
col

['member_name',
 'email',
 'phone_number',
 'school1',
 'school1최종',
 '식별자',
 'class1',
 'class2',
 'class3',
 'class4',
 '재등록 여부',
 '유입경로',
 'BDA를 알게된 인스타그램 콘텐츠',
 '콘텐츠를 보게 된 경로',
 '관심을 끌었던 인스타그램 콘텐츠',
 '관심이 없었던 인스타그램 콘텐츠',
 '등록 결정 이유(인스타그램)',
 '보고싶은 컨텐츠',
 'whyBDA',
 '재등록 여부.1',
 '기존 분반[3기]',
 '기존 분반[4기]',
 '기존 분반[5기]',
 '기존 분반[6기]',
 '기존 분반[7기]',
 '기존 분반[8기]',
 '기존 분반[9기]',
 '가장 만족한 활동(재등록)',
 '기대되는 활동(재등록)',
 '만족, 기대 답변 이유(재등록)',
 'whyBDA(재등록)',
 '내/외국인',
 '성별',
 'birthday',
 '거주지',
 '세부 거주지',
 '원하는 분반 개수',
 '원하는 활동(일반)',
 '원하는 분반 번호(1개)',
 '분반 선택 이유(1개)',
 '원하는 분반 번호(2개_1)',
 '분반 선택 이유(2개_1)',
 '원하는 분반 번호(2개_2)',
 '분반 선택 이유(2개_2)',
 '원하는 분반 번호(3개_1)',
 '분반 선택 이유(3개_1)',
 '원하는 분반 번호(3개_2)',
 '분반 선택 이유(3개_2)',
 '원하는 분반 번호(3개_3)',
 '분반 선택 이유(3개_3)',
 '프로젝트 형태',
 '조별활동 희망',
 '투입 가능 시간',
 '얻고자 하는 것',
 '최종학력',
 '재학 여부(석사)',
 'school2',
 'school2최종',
 '단과 대학(석사)',
 'major2',
 '재학 여부(학사)',
 '이수학기',
 '소속대학',
 'major1_1',
 'major type',
 '전공계열',
 'major1_2',
 'major1_3',
 'major_data',
 'job',
 'job_domain',
 'company',
 'whyBDA(현재직장)',
 '데이터 분석 역량 필요 이유(현재직장)',
 '직업 형태(현재직장)',
 '근무 연차(현재직장)',
 '직장 도메인(이전직장)',
 '직업명(이전직장)',
 '근무 연차(이전직장)',
 '데이터 분석 역량 필요 이유(이전직장)',
 '희망 진로',
 '희망 도메인',
 '희망 직무',
 '희망 직무 데이터 역량',
 '관심있는 기업명',
 '언어 숙련도(SQL)',
 '언어 숙련도(Python)',
 '언어 숙련도(R)',
 '패키지 숙련도(Pandas)',
 '패키지 숙련도(Numpy)',
 '패키지 숙련도(Scikit-learn)',
 '패키지 숙련도(Pytorch)',
 '패키지 숙련도(TensorFlow)',
 '패키지 숙련도(Keras)',
 '시각화 도구 숙련도(Looker Studio)',
 '시각화 도구 숙련도(Tableau)',
 '시각화 도구 숙련도(Power BI)',
 '시각화 도구 숙련도(Python 시각화 라이브러리)',
 '취득 자격증',
 '취득 희망 자격증',
 '희망 자격증 스터디 기간',
 '데이터 관련 활동 경험(스터디)',
 '데이터 관련 활동 경험(동아리)',
 '데이터 관련 활동 경험(학회)',
 '아쉬웠던 점(스터디, 동아리, 학회)',
 '데이터 관련 대회 경험(공모전)',
 '데이터 관련 대회 경험(프로젝트)',
 '아쉬웠던 점(공모전, 프로젝트)',
 '관심있는 채용 프로그램',
 '그 밖의 채용 프로그램',
 '원데이 클래스 주제',
 '원데이 클래스 강의 형식',
 '원데이 클래스 난이도',
 '원데이 클래스 참여할 의향',
 '원데이 클래스 요청 사항',
 'BDA WAVE 추가 컨텐츠',
 '학술제 참여 의사',
 '학술제 컨텐츠',
 '데이터 외 희망 직무',
 '원하는 현직자 수준',
 '원하는 현직자 강의 주제',
 '현직자 기업 수준',
 '현직자 강의 형식',
 '현직자 강의 규모',
 '규모 선택 이유(현직자)',
 '데이터 분석 대회 경험',
 '공모전 성능 향상 방법',
 '아이디어 공모전 기획 방법',
 '공모전 수상 경력',
 '원하는 행사(공멘토)',
 'whyBDA(공멘토)',
 '응답폼유무',
 'marketing_agree',
 'contents_agree',
 'before_id',
 'generation',
 'withdrawal',
 'member_id']

In [ ]:
df = df.drop(columns=['school1']).rename(columns={'school1최종': 'school1'})
df = df.drop(columns=['school2']).rename(columns={'school2최종': 'school2'})

In [ ]:
df_fe = df[['member_id', 'member_name', 'generation', 'birthday', 'email',
       'phone_number', 'school1', 'major1_1', 'major1_2', 'major1_3',
       'school2', 'major2', 'job', 'job_domain', 'company',
       'major_data','class1', 'class2', 'class3', 'class4', 'withdrawal',
 '재등록 여부',
 '유입경로',
 'BDA를 알게된 인스타그램 콘텐츠',
 '콘텐츠를 보게 된 경로',
 '관심을 끌었던 인스타그램 콘텐츠',
 '관심이 없었던 인스타그램 콘텐츠',
 '등록 결정 이유(인스타그램)',
 '보고싶은 컨텐츠',
 'whyBDA',
 '기존 분반[3기]',
 '기존 분반[4기]',
 '기존 분반[5기]',
 '기존 분반[6기]',
 '기존 분반[7기]',
 '기존 분반[8기]',
 '기존 분반[9기]',
 '가장 만족한 활동(재등록)',
 '기대되는 활동(재등록)',
 '만족, 기대 답변 이유(재등록)',
 'whyBDA(재등록)',
 '내/외국인',
 '성별',
 '거주지',
 '세부 거주지',
 '원하는 분반 개수',
 '원하는 활동(일반)',
 '원하는 분반 번호(1개)',
 '분반 선택 이유(1개)',
 '원하는 분반 번호(2개_1)',
 '분반 선택 이유(2개_1)',
 '원하는 분반 번호(2개_2)',
 '분반 선택 이유(2개_2)',
 '원하는 분반 번호(3개_1)',
 '분반 선택 이유(3개_1)',
 '원하는 분반 번호(3개_2)',
 '분반 선택 이유(3개_2)',
 '원하는 분반 번호(3개_3)',
 '분반 선택 이유(3개_3)',
 '프로젝트 형태',
 '조별활동 희망',
 '투입 가능 시간',
 '얻고자 하는 것',
 '최종학력',
 '재학 여부(석사)',
 '단과 대학(석사)',
 '재학 여부(학사)',
 '이수학기',
 '소속대학',
 'major type',
 '전공계열',
 '직업 형태(현재직장)',
 '근무 연차(현재직장)',
 'whyBDA(현재직장)',
 '데이터 분석 역량 필요 이유(현재직장)',
 '직장 도메인(이전직장)',
 '직업명(이전직장)',
 '근무 연차(이전직장)',
 '데이터 분석 역량 필요 이유(이전직장)',
 '희망 진로',
 '희망 도메인',
 '희망 직무',
 '희망 직무 데이터 역량',
 '관심있는 기업명',
 '언어 숙련도(SQL)',
 '언어 숙련도(Python)',
 '언어 숙련도(R)',
 '패키지 숙련도(Pandas)',
 '패키지 숙련도(Numpy)',
 '패키지 숙련도(Scikit-learn)',
 '패키지 숙련도(Pytorch)',
 '패키지 숙련도(TensorFlow)',
 '패키지 숙련도(Keras)',
 '시각화 도구 숙련도(Looker Studio)',
 '시각화 도구 숙련도(Tableau)',
 '시각화 도구 숙련도(Power BI)',
 '시각화 도구 숙련도(Python 시각화 라이브러리)',
 '취득 자격증',
 '취득 희망 자격증',
 '희망 자격증 스터디 기간',
 '데이터 관련 활동 경험(스터디)',
 '데이터 관련 활동 경험(동아리)',
 '데이터 관련 활동 경험(학회)',
 '아쉬웠던 점(스터디, 동아리, 학회)',
 '데이터 관련 대회 경험(공모전)',
 '데이터 관련 대회 경험(프로젝트)',
 '아쉬웠던 점(공모전, 프로젝트)',
 '관심있는 채용 프로그램',
 '그 밖의 채용 프로그램',
 '원데이 클래스 주제',
 '원데이 클래스 강의 형식',
 '원데이 클래스 난이도',
 '원데이 클래스 참여할 의향',
 '원데이 클래스 요청 사항',
 'BDA WAVE 추가 컨텐츠',
 '학술제 참여 의사',
 '학술제 컨텐츠',
 '데이터 외 희망 직무',
 '원하는 현직자 수준',
 '원하는 현직자 강의 주제',
 '현직자 기업 수준',
 '현직자 강의 형식',
 '현직자 강의 규모',
 '규모 선택 이유(현직자)',
 '데이터 분석 대회 경험',
 '공모전 성능 향상 방법',
 '아이디어 공모전 기획 방법',
 '공모전 수상 경력',
 '원하는 행사(공멘토)',
 'whyBDA(공멘토)',
 '식별자',
 '응답폼유무',
]]

In [ ]:
print(df['phone_number'].head())
print(df['phone_number'].dtype)

0    01058631610
1    01073063668
2    01097694955
3    01085059745
4    01063197508
Name: phone_number, dtype: object
object

In [ ]:
df_fe['phone_number'] = df['phone_number'].apply(lambda x: "'" + x)
df_fe.to_excel('10기모집폼전처리.xlsx', index=False)

<ipython-input-72-7c6d37cfb94a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fe['phone_number'] = df['phone_number'].apply(lambda x: "'" + x)

In [ ]:
df_fe

,member_id,member_name,generation,birthday,email,phone_number,school1,major1_1,major1_2,major1_3,school2,major2,job,job_domain,company,major_data,class1,class2,class3,class4,withdrawal,재등록 여부,유입경로,BDA를 알게된 인스타그램 콘텐츠,콘텐츠를 보게 된 경로,관심을 끌었던 인스타그램 콘텐츠,관심이 없었던 인스타그램 콘텐츠,등록 결정 이유(인스타그램),보고싶은 컨텐츠,whyBDA,기존 분반[3기],기존 분반[4기],기존 분반[5기],기존 분반[6기],기존 분반[7기],기존 분반[8기],기존 분반[9기],가장 만족한 활동(재등록),기대되는 활동(재등록),"만족, 기대 답변 이유(재등록)",whyBDA(재등록),내/외국인,성별,거주지,세부 거주지,원하는 분반 개수,원하는 활동(일반),원하는 분반 번호(1개),분반 선택 이유(1개),원하는 분반 번호(2개_1),분반 선택 이유(2개_1),원하는 분반 번호(2개_2),분반 선택 이유(2개_2),원하는 분반 번호(3개_1),분반 선택 이유(3개_1),원하는 분반 번호(3개_2),분반 선택 이유(3개_2),원하는 분반 번호(3개_3),분반 선택 이유(3개_3),프로젝트 형태,조별활동 희망,투입 가능 시간,얻고자 하는 것,최종학력,재학 여부(석사),단과 대학(석사),재학 여부(학사),이수학기,소속대학,major type,전공계열,직업 형태(현재직장),근무 연차(현재직장),whyBDA(현재직장),데이터 분석 역량 필요 이유(현재직장),직장 도메인(이전직장),직업명(이전직장),근무 연차(이전직장),데이터 분석 역량 필요 이유(이전직장),희망 진로,희망 도메인,희망 직무,희망 직무 데이터 역량,관심있는 기업명,언어 숙련도(SQL),언어 숙련도(Python),언어 숙련도(R),패키지 숙련도(Pandas),패키지 숙련도(Numpy),패키지 숙련도(Scikit-learn),패키지 숙련도(Pytorch),패키지 숙련도(TensorFlow),패키지 숙련도(Keras),시각화 도구 숙련도(Looker Studio),시각화 도구 숙련도(Tableau),시각화 도구 숙련도(Power BI),시각화 도구 숙련도(Python 시각화 라이브러리),취득 자격증,취득 희망 자격증,희망 자격증 스터디 기간,데이터 관련 활동 경험(스터디),데이터 관련 활동 경험(동아리),데이터 관련 활동 경험(학회),"아쉬웠던 점(스터디, 동아리, 학회)",데이터 관련 대회 경험(공모전),데이터 관련 대회 경험(프로젝트),"아쉬웠던 점(공모전, 프로젝트)",관심있는 채용 프로그램,그 밖의 채용 프로그램,원데이 클래스 주제,원데이 클래스 강의 형식,원데이 클래스 난이도,원데이 클래스 참여할 의향,원데이 클래스 요청 사항,BDA WAVE 추가 컨텐츠,학술제 참여 의사,학술제 컨텐츠,데이터 외 희망 직무,원하는 현직자 수준,원하는 현직자 강의 주제,현직자 기업 수준,현직자 강의 형식,현직자 강의 규모,규모 선택 이유(현직자),데이터 분석 대회 경험,공모전 성능 향상 방법,아이디어 공모전 기획 방법,공모전 수상 경력,원하는 행사(공멘토),whyBDA(공멘토),식별자,응답폼유무
0,2025100001,Hannah Safiah Binti Saharani,10,20030102,h.safiahx@gmail.com,'01058631610,정보없음,NaN,NaN,NaN,정보없음,NaN,대학생,A. 해당없음,NaN,False,1,NaN,NaN,NaN,False,아니요,지인 추천,NaN,NaN,NaN,NaN,NaN,NaN,"BDA 학회원만의 혜택을 누리고 싶어서(현직자 강연, 잡 페스티벌, 기업연계 공모전 등)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,외국인,여,서울특별시,서대문구,1개,NaN,1.0,시간대가 적합해서,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,개인,아니요. 개인적으로 학회 활동을 하고 싶어요,0.5,공모전 경험,대학교 학사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A. 해당없음,NaN,NaN,NaN,취업,"M. 전문, 과학 및 기술 서비스업",D. 인공지능 전문가,10.0,"삼성, 카카오, 현대,구글, 마이크로소프트",사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,없음,ADsP,접수일 전 5주,0회,0회,0회,참여 경험 없음,0회,0회,참여 경험 없음,"포트폴리오 (예시: UI/UX 디자인 포트폴리오 템플릿 제공, 첨삭 등)",NaN,AI모델 구축,프로젝트 기반,입문자 대상 (원데이 클래스 주제와 관련된 경험이 거의 없음),3.0,NaN,학술제,예,IT 콘텐츠,A. 금융 / 보험 직무,주니어 (0~3년차),산업 트렌드 (예시: ChatGPT로 인한 직무 변화),국내 빅테크 IT 계열 (네카라쿠배당토),온라인,100명 이상의 리스너와 10명 이상의 현직자,많은 참가자 선호,NaN,NaN,NaN,NaN,NaN,NaN,Hannah Safiah Binti Saharani_16,True
1,2025100002,Ngoc Vu (알렉스),10,20030323,alex.vnbn@gmail.com,'01073063668,연세대학교 본교,창의기술경영학과,NaN,NaN,정보없음,NaN,대학생,A. 해당없음,NaN,False,14,NaN,NaN,NaN,False,아니요,에브리타임,NaN,NaN,NaN,NaN,NaN,NaN,현직자의 강의를 듣고 싶어서,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,외국인,여,인천광역시,연수구,1개,NaN,14.0,해당 분반의 주제에 관심이 있어서,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,개인,아니요. 개인적으로 학회 활동을 하고 싶어요,1.5,데이터 분석 역량,대학교 학사,NaN,NaN,재학,5.0,연세대학교 서울캠퍼스,단일 전공,"경영학, 경제통상학",NaN,NaN,NaN,NaN,A. 해당없음,NaN,NaN,NaN,취업,J. 정보통신업,B. 데이터 분석가,10.0,카카오,초급,초급,사용해본 적 없음,초급,초급,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,초급,초급,초급,"ADsP, SQLD, 빅데이터 분석 기사",빅데이터 분석 기사,접수일 전 5주,2회,0회,0회,"참여도 저하, 커뮤니케이션 부족, 기대와의 불일치",0회,2회,"참여도 저하, 피드백 부족, 결과에 대한 불만족, 능력에 대한 아쉬움","포트폴리오 (예시: UI/UX 디자인 포트폴리오 템플릿 제공, 첨삭 등)",NaN,"Python 응용 (ex- 머신러닝을 이용한 추천시스템 구축), Tableau를 이...",실습 중심 (Hands-on),입문자 대상 (원데이 클래스 주제와 관련된 경험이 거의 없음),5.0,NaN,없음,예,없음,"B. 기획 / 전략 / 경영 직무, D. 소프트웨어 개발자, F. PM / 서비스 기획자",시니어 (10년차 ~),커리어 패스 과정 (예시: 비전공자/전공자의 취업 준비 및 이직 과정),해외 기업 (빅테크),온라인,10명 내외의 강의 리스너와 1명의 현직자,인원이 적어야 집중할 수 있어서,NaN,NaN,NaN,NaN,NaN,NaN,Ngoc Vu (알렉스)_36,True
2,2025100003,Nur Izzatty Binti Mohamad Jamal,10,19950228,izzattyjamal28@gmail.com,'01097694955,이화여자대학교,Faculty of Resources Science and Technology 학과...,없음,없음,연세대학교 본교,혁신학과,대학원생,A. 해당없음,NaN,False,1,NaN,NaN,NaN,False,아니요,인스타그램,지인의 콘텐츠 공유,지인의 콘텐츠 공유,BDA 10기 학회원 모집 콘텐츠,BDA BOOTCAMP 안내/후기,학회원 행사 및 혜택,최신 기술 동향 및 정보,"BDA 학회원만의 혜택을 누리고 싶어서(현직자 강연, 잡 페스티벌, 기업연계 공모전 등)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,외국인,여,서울특별시,관악구,1개,NaN,1.0,"기초적인 내용을 배우고 싶어서(예: 파이썬 문법, SQL, R)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,개인,아니요. 개인적으로 학회 활동을 하고 싶어요,4.0,데이터 분석 역량,대학교 석사 이상,재학,IT (컴퓨터 공학 포함),재학,4.0,University Malaysia Sarawak 대학교,단일 전공,IT (컴퓨터 공학 포함),NaN,NaN,NaN,NaN,A. 해당없음,NaN,NaN,NaN,취업,U. 국제 및 외국기관,G. PM/서비스 기획자,8.0,"Google, Amazon",사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,없음,구글 애널리스트,접수일 전 5주,0회,0회,0회,시간 부족(학업 및 일과 병행 어려움),0회,0회,시간 부족(학업 및 일과 병행 어려움),"산업 트렌드 (예시: ChatGPT로 인한 직무 변화, AI에 따른 산업 이슈 등)",NaN,"Python 응용 (ex- 머신러닝을 이용한 추천시스템 구축), AI모델 구축, 데...",실습 중심 (Hands-on),입문자 대상 (원데이 클래스 주제와 관련된 경험이 거의 없음),4.0,NaN,-,예,-,"A. 금융 / 보험 직무, E. UI/UX 디자이너, F. PM / 서비스 기획자",시니어 (10년차 ~),산업 트렌드 (예시: ChatGPT로 인한 직무 변화),해외 기업 (빅테크),"온, 오프라인 동시",100명 이상의 리스너와 10명 이상의 현직자,10명 이상의 현직자의 다양한 경험과 인사이트를 한 번에 들을 수 있어서 선택했습니다,NaN,NaN,NaN,NaN,NaN,NaN,Nur Izzatty Binti Mohamad Jamal_49,True
3,2025100004,강동운,10,20011116,rvescd@gmail.com,'01085059745,가천대학교,응용통계학과,없음,없음,정보없음,NaN,대학생,A. 해당없음,NaN,True,15,NaN,NaN,NaN,False,예,인스타그램,스토리,인스타그램 스토리에서 본 콘텐츠,데이터 분야 채용 공고 모음.zip,알고보면 쓸데있는 데이터 잡학사전,실질적인 정보 제공,학습 커리큘럼 상세 소개,현직자의 강의를 듣고 싶어서,해당없음,해당없음,해당없음,해당없음,해당없음,해당없음,0006 : 데이터 분석 전처리반(판다스),현직자의 강의와 복습 및 필수 과제,BDA 내부 공모전,학사 일정과 학회 일정이 맞지않아 성실히 참여하지 못한 것이 아쉽습니다. 다시 한번...,강의의 퀄리티와 현직자 강연 및 원데이 클래스,내국인,남,경기도,수장구,1개,NaN,15.0,"특정 기술이나 언어를 심화 학습하기 위해(예: 머신러닝, 통계, 판다스)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,팀,아니요. 개인적으로 학회 활동을 하고 싶어요,2.0,프로젝트 경험,대학교 학사,NaN,NaN,휴학,6.0,가천대학교 글로벌캠퍼스,단일 전공,사회과학,NaN,NaN,NaN,NaN,A. 해당없음,NaN,NaN,NaN,취업,K. 금융 및 보험업,B. 데이터 분석가,7.0,하나은행,초급,중급,중급,중급,중급,초급,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,중급,"ADsP, SQLD","빅데이터 분석 기사, 정보처리기사",접수일 전 4주,1회,1회,0회,참여도 저하,2회,1회,결과에 대한 불만족,"실무자와의 만남 (네트워킹, 멘토링, 커피챗 등)",NaN,Python 응용 (ex- 머신러닝을 이용한 추천시스템 구축),프로젝트 기반,중급자 대상 (원데이 클래스 주제에 대한 기본 경험이 있음),5.0,NaN,프로젝트 PT,예,.,A. 금융 / 보험 직무,주니어 (0~3년차),커리어 패스 과정 (예시: 비전공자/전공자의 취업 준비 및 이직 과정),"국내 대기업 IT 계열 (금융, 제조 ...)","온, 오프라인 동시",3~50명 내외의 강의 리스너와 1명의 현직자,다양한 질문과 답변을 얻을 수 있어사,NaN,NaN,NaN,NaN,NaN,NaN,강동운_97,True
4,2025100005,강두원,10,20010926,danbean2013@gmail.com,'01063197508,세종대학교,데이터사이언스학과,없음,없음,정보없음,NaN,대학생,A. 해당없음,NaN,True,4,NaN,NaN,NaN,False,아니요,에브리타임,NaN,NaN,NaN,NaN,NaN,NaN,혼자 공부하기 어려워서,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,내국인,남,서울특별시,강남구,1개,NaN,4.0,"특정 기술이나 언어를 심화 학습하기 위해(예: 머신러닝, 통계, 판다스)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,개인,네. 온라인으로 참여하고 싶어요,2.0,데이터 분석 역량,대학교 학사,NaN,NaN,재학,4.0,세종대학교,단일 전공,IT (컴퓨터 공학 포함),NaN,NaN,NaN,NaN,A. 해당없음,NaN,NaN,NaN,취업,J. 정보통신업,A. 데이터 엔지니어,10.0,토스,사용해본 적 없음,초급,초급,사용해본 적 없음,초급,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,없음,"ADsP, SQLD, 빅데이터 분석 기사",시험일 전 4주,0회,0회,0회,참여 경험 없음,1회,0회,능력에 대한 아쉬움,"채용 설명회 및 상담 (예시: 기업별 인재상 탐색, 기업 전사적 이슈 및 직무 이슈...",없음,"Python 응용 (ex- 머신러닝을 이용한 추천시스템 구축), SQL 응용",이론 중심,입문자 대상 (원데이 클래스 주제와 관련된 경험이 거의 없음),4.0,NaN,해커톤,예,없음,D. 소프트웨어 개발자,주니어 (0~3년차),커리어 패스 과정 (예시: 비전공자/전공자의 취업 준비 및 이직 과정),국내 빅테크 IT 계열 (네카라쿠배당토),"온, 오프라인 동시",10명 내외의 강의 리스너와 1명의 현직자,인원이 적어야 원활한 질의응답이 가능할 것 같아서,NaN,NaN,NaN,NaN,NaN,NaN,강두원_75,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,2025100914,황정민,10,20000119,hjm8625@hanyang.ac.kr,'01092538625,한양대학교 본교,융합전자공학부,NaN,NaN,정보없음,NaN,대학생,A. 해당없음,NaN,False,2,NaN,NaN,NaN,False,예,기존 BDA 오픈채팅방,NaN,NaN,NaN,NaN,NaN,NaN,혼자 공부하기 어려워서,해당없음,해당없음,해당없음,해당없음,해당없음,해당없음,0006 : 데이터 분석 전처리반(판다스),현직자의 강의와 복습 및 필수 과제,현직자의 강의와 복습 및 필수 과제,공부하기 수월했다,저번에 만족했다,내국인,남,서울특별시,성동구,1개,NaN,2.0,"기초적인 내용을 배우고 싶어서(예: 파이썬 문법, SQL, R)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,개인,아니요. 개인적으로 학회 활동을 하고 싶어요,3.0,데이터 분석 역량,대학교 학사,NaN,NaN,재학,5.0,한양대학교 서울캠퍼스,단일 전공,공학 (컴퓨터 공학 제외),NaN,NaN,NaN,NaN,A. 해당없음,NaN,NaN,NaN,취업,"M. 전문, 과학 및 기술 서비스업",C. 데이터 사이언티스트,10.0,엔비디아,사용해본 적 없음,중급,사용해본 적 없음,초급,초급,초급,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,초급,없음,SQLD,시험일 전 3주,1회,1회,0회,"시간 부족(학업 및 일과 병행 어려움), 참여도 저하, 기대와의 불일치",0회,0회,능력에 대한 아쉬움,"실무자와의 만남 (네트워킹, 멘토링, 커피챗 등)",NaN,"Python 응용 (ex- 머신러닝을 이용한 추천시스템 구축), Tableau를 이...",프로젝트 기반,중급자 대상 (원데이 클래스 주제에 대한 기본 경험이 있음),4.0,NaN,프로젝트 추천,예,현직자들의 피드백,D. 소프트웨어 개발자,주니어 (0~3년차),커리어 패스 과정 (예시: 비전공자/전공자의 취업 준비 및 이직 과정),국내 빅테크 IT 계열 (네카라쿠배당토),오프라인,3~50명 내외의 강의 리스너와 1명의 현직자,1대 50 정도가 집중하기 적당한것 같다,NaN,NaN,NaN,NaN,NaN,NaN,황정민_86,True
914,2025100915,황종서,10,20040403,jongseo9955@gmail.com,'01099553477,연세대학교 본교,기계공학부,없음,없음,정보없음,NaN,대학생,A. 해당없음,NaN,False,4,NaN,NaN,NaN,False,아니요,에브리타임,NaN,NaN,NaN,NaN,NaN,NaN,시간적으로 부담이 없어서,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,내국인,남,경기도,평택시,1개,NaN,4.0,"특정 기술이나 언어를 심화 학습하기 위해(예: 머신러닝, 통계, 판다스)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,팀,네. 온라인으로 참여하고 싶어요,2.0,데이터 분석 역량,대학교 학사,NaN,NaN,휴학,3.0,연세대학교 신촌캠퍼스,단일 전공,공학 (컴퓨터 공학 제외),NaN,NaN,NaN,NaN,A. 해당없음,NaN,NaN,NaN,대학원 진학,"M. 전문, 과학 및 기술 서비스업",로보틱스 연구원,8.0,없음,사용해본 적 없음,초급,사용해본 적 없음,초급,초급,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,초급,없음,정보처리기사,접수일 전 4주,0회,0회,0회,참여 경험 없음,0회,0회,참여 경험 없음,직무 강의 (예시: 실무 진행 방식 및 직무 준비생을 위한 팁),NaN,"Python 응용 (ex- 머신러닝을 이용한 추천시스템 구축), AI모델 구축",실습 중심 (Hands-on),입문자 대상 (원데이 클래스 주제와 관련된 경험이 거의 없음),4.0,NaN,없음,아니오,없음,D. 소프트웨어 개발자,주니어 (0~3년차),직무 강의 (예시: 실무 진행 방식 및 직무 준비생을 위한 팁),"국내 대기업 IT 계열 (금융, 제조 ...)",온라인,100명 이상의 리스너와 10명 이상의 현직자,온라인이라면 인원이 많을수록 좋을 것 같습니다,NaN,NaN,NaN,NaN,NaN,NaN,황종서_34,True
915,2025100916,황준영,10,20030209,junyh29@gmail.com,'01036658637,중앙대학교 제1캠퍼스,에너지시스템공학부,없음,없음,정보없음,NaN,대학생,A. 해당없음,NaN,False,4,16,NaN,NaN,False,아니요,인스타그램,피드 게시물,지인의 콘텐츠 공유,BDA 10기 학회원 모집 콘텐츠,기타 학회 내부 소식,실질적인 정보 제공,학습 커리큘럼 상세 소개,현직자의 강의를 듣고 싶어서,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,내국인,남,경기도,부천시,2개,NaN,NaN,NaN,4.0,해당 분반의 주제에 관심이 있어서,16.0,해당 분반의 주제에 관심이 있어서,NaN,NaN,NaN,NaN,NaN,NaN,팀,네. 오프라인으로 참여하고 싶어요,2.0,프로젝트 경험,대학교 학사,NaN,NaN,재학,6.0,중앙대학교 서울캠퍼스,단일 전공,공학 (컴퓨터 공학 제외),NaN,NaN,NaN,NaN,A. 해당없음,NaN,NaN,NaN,대학원 진학,"M. 전문, 과학 및 기술 서비스업",D. 인공지능 전문가,8.0,두산에너빌리티,사용해본 적 없음,초급,사용해본 적 없음,초급,초급,사용해본 적 없음,초급,초급,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,초급,없음,정보처리기사,접수일 전 5주,0회,0회,0회,참여 경험 없음,0회,0회,참여 경험 없음,"산업 트렌드 (예시: ChatGPT로 인한 직무 변화, AI에 따른 산업 이슈 등)",NaN,Python 응용 (ex- 머신러닝을 이용한 추천시스템 구축),실습 중심 (Hands-on),입문자 대상 (원데이 클래스 주제와 관련된 경험이 거의 없음),3.0,NaN,없움,예,없음,"D. 소프트웨어 개발자, G. 자연과학계열 연구자",시니어 (10년차 ~),산업 트렌드 (예시: ChatGPT로 인한 직무 변화),해외 기업 (빅테크),"온, 오프라인 동시",100명 이상의 리스너와 10명 이상의 현직자,여러명의 전문가에게 여러 시선에 대해 듣고 싶어서,NaN,NaN,NaN,NaN,NaN,NaN,황준영_86,True
916,2025100917,황지영,10,20021205,jihwangww@gmail.com,'01050552321,경북대학교,컴퓨터학부,NaN,NaN,정보없음,NaN,대학생,A. 해당없음,NaN,True,4,5,NaN,NaN,False,아니요,인스타그램,인스타그램 광고,인스타그램 스토리에서 본 콘텐츠,데이터 분야 공모전 모음.zip,기타 학회 내부 소식,실질적인 정보 제공,최신 기술 동향 및 정보,"BDA 학회원만의 혜택을 누리고 싶어서(현직자 강연, 잡 페스티벌, 기업연계 공모전 등)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,내국인,여,부산광역시,서면,2개,NaN,NaN,NaN,4.0,해당 분반의 주제에 관심이 있어서,5.0,해당 분반의 주제에 관심이 있어서,NaN,NaN,NaN,NaN,NaN,NaN,개인,아니요. 개인적으로 학회 활동을 하고 싶어요,3.0,데이터 분석 역량,대학교 학사,NaN,NaN,재학,6.0,경북대학교 대구캠퍼스,단일 전공,IT (컴퓨터 공학 포함),NaN,NaN,NaN,NaN,A. 해당없음,NaN,NaN,NaN,대학원 진학,"M. 전문, 과학 및 기술 서비스업",C. 데이터 사이언티스트,10.0,Google,사용해본 적 없음,초급,사용해본 적 없음,초급,초급,초급,초급,초급,초급,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,초급,없음,없음,접수일 전 4주,0회,0회,0회,참여 경험 없음,0회,0회,참여 경험 없음,"자소서 & 인적성 관련 (예시: 산업군별 자소서 특강 및 1:1 첨삭, 인적성 풀이...",NaN,"AI모델 구축, SQL 응용",실습 중심 (Hands-on),입문자 대상 (원데이 클래스 주제와 관련된 경험이 거의 없음),5.0,NaN,없음,예,논문 발표 & 피드백,D. 소프트웨어 개발자,주니어 (0~3년차),직무 강의 (예시: 실무 진행 방식 및 직무 준비생을 위한 팁),국내 빅테크 IT 계열 (네카라쿠배당토),온라인,3~50명 내외의 강의 리스너와 1명의 현직자,소규모는 너무 적고 적당한 규모의 인원이 있어야 집중할 수 있어서 & 질문하기 편함,NaN,NaN,NaN,NaN,NaN,NaN,황지영_23,True
917,2025100918,황지희,10,20030825,ghkdwlgml0825@gmail.com,'01062687360,연세대학교 본교,계량위험관리학과,없음,없음,정보없음,NaN,대학생,L. 금융 및 보험업,연구지원 보조,False,12,15,NaN,NaN,False,아니요,에브리타임,NaN,NaN,NaN,NaN,NaN,NaN,혼자 공부하기 어려워서,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,내국인,여,서울특별시,강남구,2개,NaN,NaN,NaN,12.0,"기초적인 내용을 배우고 싶어서(예: 파이썬 문법, SQL, R)",15.0,"특정 기술이나 언어를 심화 학습하기 위해(예: 머신러닝, 통계, 판다스)",NaN,NaN,NaN,NaN,NaN,NaN,개인,네. 오프라인으로 참여하고 싶어요,1.0,프로젝트 경험,대학교 학사,NaN,NaN,휴학,6.0,연세대학교,단일 전공,경제통상학,인턴,0~6개월,데이터 능력을 함양하기 위해,업무를 더 효율적으로 하기 위해,A. 해당없음,NaN,NaN,NaN,취업,K. 금융 및 보험업,데이터 직무는 아님,4.0,"증권사, 자산운용사",초급,중급,초급,중급,중급,초급,초급,초급,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,사용해본 적 없음,중급,"ADsP, SQLD, 구글 애널리스트","빅데이터 분석 기사, 정보처리기사, 컴퓨터 활용능력(1,2급)",시험일 전 5주,1회,0회,0회,기대와의 불일치,0회,2회,능력에 대한 아쉬움,직무 강의 (예시: 실무 진행 방식 및 직무 준비생을 위한 팁),NaN,"Python 응용 (ex- 머신러닝을 이용한 추천시스템 구축), SQL 응용",프로젝트 기반,중급자 대상 (원데이 클래스 주제에 대한 기본 경험이 있음),4.0,NaN,자기소개서 첨삭,아니오,따로 없습니다.,A. 금융 / 보험 직무,주니어 (0~3년차),직무 강의 (예시: 실무 진행 방식 및 직무 준비생을 위한 팁),"국내 대기업 IT 계열 (금융, 제조 ...)","온, 오프라인 동시",100명 이상의 리스너와 10명 이상의 현직자,더 많은 현직자 분들을 뵙고 싶습니다.,NaN,NaN,NaN,NaN,NaN,NaN,황지희_73,True

In [ ]:
nan_data = df[df['member_name'].isna()]
nan_data

Empty DataFrame
Columns: [member_name, email, phone_number, school1, 식별자, class1, class2, class3, class4, 재등록 여부, 유입경로, BDA를 알게된 인스타그램 콘텐츠, 콘텐츠를 보게 된 경로, 관심을 끌었던 인스타그램 콘텐츠, 관심이 없었던 인스타그램 콘텐츠, 등록 결정 이유(인스타그램), 보고싶은 컨텐츠, whyBDA, 재등록 여부.1, 기존 분반[3기], 기존 분반[4기], 기존 분반[5기], 기존 분반[6기], 기존 분반[7기], 기존 분반[8기], 기존 분반[9기], 가장 만족한 활동(재등록), 기대되는 활동(재등록), 만족, 기대 답변 이유(재등록), whyBDA(재등록), 내/외국인, 성별, birthday, 거주지, 세부 거주지, 원하는 분반 개수, 원하는 활동(일반), 원하는 분반 번호(1개), 분반 선택 이유(1개), 원하는 분반 번호(2개_1), 분반 선택 이유(2개_1), 원하는 분반 번호(2개_2), 분반 선택 이유(2개_2), 원하는 분반 번호(3개_1), 분반 선택 이유(3개_1), 원하는 분반 번호(3개_2), 분반 선택 이유(3개_2), 원하는 분반 번호(3개_3), 분반 선택 이유(3개_3), 프로젝트 형태, 조별활동 희망, 투입 가능 시간, 얻고자 하는 것, 최종학력, 재학 여부(석사), school2, 단과 대학(석사), major2, 재학 여부(학사), 이수학기, 소속대학, major1_1, major type, 전공계열, major1_2, major1_3, major_data, job, job_domain, company, whyBDA(현재직장), 데이터 분석 역량 필요 이유(현재직장), 직업 형태(현재직장), 근무 연차(현재직장), 직장 도메인(이전직장), 직업명(이전직장), 근무 연차(이전직장), 데이터 분석 역량 필요 이유(이전직장), 희망 진로, 희망 도메인, 희망 직무, 희망 직무 데이터 역량, 관심있는 기업명, 언어 숙련도(SQL), 언어 숙련도(Python), 언어 숙련도(R), 패키지 숙련도(Pandas), 패키지 숙련도(Numpy), 패키지 숙련도(Scikit-learn), 패키지 숙련도(Pytorch), 패키지 숙련도(TensorFlow), 패키지 숙련도(Keras), 시각화 도구 숙련도(Looker Studio), 시각화 도구 숙련도(Tableau), 시각화 도구 숙련도(Power BI), 시각화 도구 숙련도(Python 시각화 라이브러리), 취득 자격증, 취득 희망 자격증, 희망 자격증 스터디 기간, 데이터 관련 활동 경험(스터디), ...]
Index: []

In [ ]:
# 세부 거주지에서 거주지 정보가 앞에 붙어 있으면 제거
df_fe['세부 거주지'] = df_fe.apply(
    lambda row: row['세부 거주지'].replace(row['거주지'], '').strip()
    if isinstance(row['세부 거주지'], str) and isinstance(row['거주지'], str)
    else row['세부 거주지'],
    axis=1
)

# 결과 확인
print(df_fe[['거주지', '세부 거주지']])

       거주지 세부 거주지
0    서울특별시   서대문구
1    인천광역시    연수구
2    서울특별시    관악구
3      경기도    수장구
4    서울특별시    강남구
..     ...    ...
913  서울특별시    성동구
914    경기도    평택시
915    경기도    부천시
916  부산광역시     서면
917  서울특별시    강남구

[918 rows x 2 columns]

<ipython-input-75-973db9c6633c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fe['세부 거주지'] = df_fe.apply(

In [ ]:
# 작은 따옴표 제거
df_fe['phone_number'] = df_fe['phone_number'].str.lstrip("'").str.strip()

# 다시 저장
df_fe.to_excel('features10_clean.xlsx', index=False)

# 경로 지정해서 저장
save_path = '/content/drive/MyDrive/BDA 6기 운영진/6기 데이터팀/김지민/features10_clean.xlsx'  # 원하는 경로로 바꿔도 돼
df_fe.to_excel(save_path, index=False)

<ipython-input-76-ff6726d5749b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fe['phone_number'] = df_fe['phone_number'].str.lstrip("'").str.strip()